<a href="https://colab.research.google.com/github/Suchada2000/test2/blob/main/Untitled14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [98]:
df = pd.read_excel('/content/drive/MyDrive/test/AB08-Study-Leave-Record_V00-ให้ นศ ช่วย cleansing.xlsx')

In [59]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,ดูข้อมูลจาก ประเภทการลาศึกษา ชีต LoVs,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,id,sequence,statuslist-อ้อม,ประเภทการลา,details,studylevel-ลิเดีย,Reason,sday,eday,place-เตย,location,country-แอน,country,scholarship,reference
1,100008,2,ฝึกอบรม ณ ต่างประเทศ,ไปฝึกอบรม ณ ต่างประเทศ,ภาษาญี่ปุ่น,NaN,NaN,1995-09-25,1996-07-09,Japan Foundation Japanese-Language Institute,Japan Foundation Japanese-Language Institute,แคนาดา,ญี่ปุ่น,The Japan Foundation Japanese Language Insititute,มข.3023/38 ลว.8ก.ย.38
2,100008,3,ลาศึกษาในประเทศ,ลาศึกษาในประเทศ,วิชาญี่ปุ่นศึกษา,ปริญญาโท,ปริญญาโท,1999-07-01,2001-06-30,มหาวิทยาลัยธรรมศาสตร์,มหาวิทยาลัยธรรมศาสตร์,ไทย,ไทย,ส่วนตัว,มข.1889/42 ลว.2 ก.ค.42
3,100008,4,ลาศึกษา ณ ต่างประเทศ,ลาศึกษา ณ ต่างประเทศ,ภาษาญี่ปุ่น,ปริญญาโท,NaN,2001-03-31,2002-03-30,Keio University,Keio University,ญี่ปุ่น,ญี่ปุ่น,Keio University Graduate Scholarship,มข.1479/44 ลว.20 มิ.ย.44
4,100009,5,ลาศึกษา ณ ต่างประเทศ,ลาศึกษา ณ ต่างประเทศ,Operative Dentistry,ปริญญาโท-เอก,NaN,1997-04-25,2002-10-24,Indiana University,Indiana University,สหรัฐอเมริกา,สหรัฐอเมริกา,รัฐบาล (ทบวงมหาวิทยาลัย),มข.1640/40 ลว.16 พ.ค.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230063,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN
230064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN

In [117]:
selected_column = df['ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ']

In [105]:
selected_column

0                   country-แอน
1                        แคนาดา
2                           ไทย
3                       ญี่ปุ่น
4                  สหรัฐอเมริกา
                  ...
230063                      NaN
230064                      NaN
230065                      NaN
230066                      NaN
230067
Name: ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ, Length: 230068, dtype: object

In [118]:
unique_values = selected_column.unique()

In [119]:
unique_values

array(['country-แอน', 'แคนาดา', 'ไทย', 'ญี่ปุ่น', 'สหรัฐอเมริกา',
       'ออสเตรเลีย', 'อังกฤษ', 'อิตาลี', 'นิวซีแลนด์', 'สิงค์โปร์', 'จีน',
       'สหราชอาณาจักร', 'ลาว', 'เยอรมัน', 'ฟิลิปปินส์', 'มาเลเซีย',
       'ฮ่องกง', 'ยูโกสลาเวีย', 'เนเธอร์แลนด์', 'ปากีสถาน', 'เกาหลีใต้',
       'ไอร์แลนด์', 'เวียดนาม', 'อินเดีย', 'สวีเดน', 'เอธิโอเปีย',
       'ออสเตรีย', 'กรีซ', 'เกาหลี', 'สาธารณรัฐประชาธิปไตยประชาชนลาว',
       'อิสราเอล', 'เบลเยี่ยม', 'ไต้หวัน', 'สวิสเซอร์แลนด์', 'ฝรั่งเศส',
       'อินโดนีเซีย', 'สกอตแลนด์', 'กัมพูชา', 'สาธารณรัฐเชค', 'นอร์เวย์',
       'เชคโกสโลวาเกีย', 'ฮังการี', 'แทนซาเนีย', 'สาธารณรัฐประชาชนจีน',
       'เมียนมาร์', 'รัสเซีย', 'สาธารณรัฐออสเตรีย', 'โปร์แลนด์',
       'เดนมาร์ค', 'บรูไน', 'โครเอเซีย',
       'สหราชอาณาจักรบริเตนใหญ่และไอร์แลนด์เหนือ', 'สเปน', 'ศรีลังกา',
       'โมนาโค', 'ราชอาณาจักรนอร์เวย์', 'เนปาล', nan, 'สาธารณรัฐอิตาลี',
       'อเมริกกา', 'ชิลี', 'เยอรมันนี', 'Lao', 'แอฟริกาใต้', 'โปรตุเกส',
       'เม็กซิโก', 'สหพันธ์สาธารณรัฐเยอรมนี', 'Czech Republic', 'ดูไบ',
       'อัฟริกาใต้', 'บราซิล', 'ตุรกี', 'มัลดีฟล์', 'มองโกเลีย',
       'สหภาพพม่า', 'สาธารณรัฐอิสลามปากีสถาน', 'สหรัฐอาหรับเอมิเรตส์',
       'บังคลาเทศ', 'ฟินแลนด์', 'ควีนส์แลนด์', 'สิงคโปร์', 'อาร์เจนตินา',
       'ราชอาณาจักรภูฏาน', 'United Arab Emirates', 'ลักเซมเบิร์ก',
       'อียิปต์', 'กาตาร์', 'กรีก', 'สาธารณรัฐอาหรับอียิปต์',
       'สาธารณรัฐโปรตุเกส', 'สาธารณรัฐอาหรับเอมิเรสต์', 'โรมาเนีย',
       'Beigium', 'สหพันธ์สาธารณรัฐเยอมณี', 'สาธารณรัฐลัตเวีย', 'นอกคณะ',
       'ในคณะ', 'สาธารณรัฐเกาหลีใต้', 'ภูฏาน', 'เลบานอน',
       'ประเทศฮ่องกงและสาธารณรัฐประชาชนจีน', 'เวียดนาม/ลาว',
       'ออสเตรเลีย/นิวซีแลนด์', 'อ่องกง', 'สมาพันธรัฐสวิส', 'สโลวาเนีย',
       'จอร์แดน', 'เดนมาร์ก', 'เครือรัฐออสเตรเลีย',
       'สาธารณรัฐอินโดนีเซีย', 'กาน่า', 'พม่า', 'สาธารณรัฐฟิจิ',
       'Saudi Arabia', 'สาธารณรัฐคิวบา', 'Austria', 'โปแลนด์',
       'สาธารณรัฐไซปรัส', 'บอตสวานา', 'สาธารณรัฐสิงคโปร์', 'เคนยา',
       'Burkina Faso', 'สหพันธรัฐสวิส', 'สาธารณรัฐสังคมนิยมเวียดนาม',
       'สาธารณรัฐมอลตา', 'เช็ก', 'ฝรั่งเศสและออสเตรีย', 'สาธารณรัฐจีน',
       'ลาว ลาว และ เวียดนาม', 'พิลิปปินส์', 'สปป.ลาว', 'ในประเทศ',
       'เยอรมนี', 'จีน (ใต้หวัน)', 'สวิสเซอร์แลนด์ และประเทศฝรั่งเศส',
       'อูกันดา', 'ตูนีเซีย', 'กรุงเทพฯ', 'สวิตเซอร์แลนด์',
       'ลาว เวียดนาม จีน', 'Turkey', 'Brunei', 'Australia', 'England',
       'ประเทศสาธารณรัฐประชาชนจีน', 'ประเทศบราซิล', 'สาธารณรัฐเกาหลี',
       'มาดากัสการ์โมซัมบิก และแอฟริกาใต้', 'ราชอาณาจักรเนเธอแลนด์',
       'สาธารณรัฐนามิเบีย', 'Japan', 'ราชอานาจักรกัมพูชา',
       'สาธารณรัฐประชาธิปไตยประชาชนลาว/ประเทศเวียดนาม',
       'ลาว/เวียดนาม/ สาธารณรัฐประชาชนจีน', 'ประเทศจีน/เวียดนาม/ลาว',
       'ประเทศไต้หวัน', 'Hong Kong', 'ยูเครน', 'ห้องประชุมนพดล ทองโสภิต',
       'Germany', 'อังกฤษ/ฝรั่งเศล',
       'เยอรมันนี เนเธอร์แลนด์ เบลเยี่ยม ลักเซมเบอร์ก',
       'นอร์เวย์และสวีเดน', 'สเปน ฝรั่งเศส อิตาลี สวิสเซอร์แลนด์',
       'Singapore', 'Spain', 'Micronesia', 'เฮติ', 'Haiti',
       'สโลวาเนียและประเทศเยอรมัน', 'ประเทศใต้หวัน',
       'ห้องประชุมจำลอง   มุ่งการดี ชั้น 4  อาคารสมเด็จพระ', 'ไืทย',
       'อิตา', 'ประเทศเวียดนาม', 'มาเลเซีย/สิงค์โปร์', 'ฝรั่งเศษ',
       'เกาหลีและจีน', 'ฮ่องกงและเกาหลีใต้', 'ประเทศสาธารณรัฐเกาหลี',
       'สิบสองปันนาสาธารณรัฐประชาชนจีน', 'ประเทศฮ่องกง',
       'สาธารณรัฐไต้หวัน', 'ประเทศสิงค์โปร์', 'ตุรกรี',
       'มาเลเซีย  และสิงคโปร์', 'ไ', 'สปน', 'CHINA',
       'สวิสเซอร์แลนด์ และ อิตาลี',
       'อังกฤษ/สวิสเซอร์แลนด์/เดนมาร์ก/ไอแลนด์', 'ไิทย', 'Malta',
       'เวียตนาม', 'ประเทศฟิลิปปินส์', 'อิตาลี / ฝรั่งเศส', 'ลาว / จีน',
       'Mongoltia', 'สาธารณรัฐมัลดีฟล์',
       'ประเทศสิงค์โปร์บริษัท เฮ็ลธ อินโนเวณัน จำกัด',
       'ราชอาณาจักรสวีเดน', 'ลาว/เวียดนาม/กัมพูชา',
       'นิวซีแลนด์/ออสเตรเลีย', 'เวียนามและจีน', 'ภูฏาณ',
       'เกาหลีและฮ่องกง', 'สหภาพพม่า  สาธารณรัฐประชาชนจีน', 'Lithuania',
       'ลิธัวเนีย', 'ประเทศมาเลเซีย', 'สวิสเซอร์แลนด์โปรตุเกส',
       'ราชอาณาจักรกัมพูชา', 'ราชอาณาจักรกัมพูชาทุน',
       'ราชอาณาจักรเนเธอร์แลนด์', 'สาธารณรัฐประชาธิปไตยประชาชาลาว',
       'สาธารณัฐประชาธิปไตยประชาชนลาว', 'สหราชอาณาจักร,เนเธอแลนด์',
       'ราชอาณาจักรสเปน', 'มาเลเซียและสิงคโปร์', 'สาธารณรัฐส้งคโปร์',
       'สาธารณรัฐสังคมนิมเวียดนาม', 'สหพันธรัฐรัสเซีย',
       'ไืทยในส่วนราชการ', 'ศธ 0514.7.3.13/ว2636/54', 'ออสเตรเลียและเชค',
       'seychelles', 'สาธารณรัฐไอร์แลนด์', 'โมร็อกโค',
       'เยอรมัน,ฝรั่งเศส,อังกฤษ',
       'ไต้หวันศธ0514.26....1.1/467  ลว. 15 .ก.พ.55', 'เกาลีใต้', 'เช็ค',
       'ไต้หวัน1', 'สหรัฐเม็กซิโก', 'สาธารณรัฐสิงค์โปร์',
       'ประเทศออสเตรเลีย', 'สาธารณรัญอินเดีย', 'สาธารณรัฐฟิลิปปินส์',
       'สาธารณรัฐฝรั่งเศส', 'ิอิตาลี', 'สาธารณรัฐตุรกี',
       'ราชอาณาจักรนอรเวย์', 'Italy', 'อินโดนีเซีย/ประเทศจีน', 'ไำทย',
       'Switzerland และ  Italy', 'สาะรณรัฐประชาธิปไตยประชาชนลาว',
       'เขตบริหารพิเศษฮ่องกงแห่งสาธารณรัฐประชาชนจีน',
       'ห้องประุมสมาคมศิษย์เก่า เวลา 12.00-13.00 น.', 'Korea', 'vietnam',
       'สาธารณรัฐอินเดีย', 'ฮ่องกง สาธารณับประชาชนขจีน',
       'สาธารรัณสังคมนิยมเวียดนาม', 'South Korea', 'ประเทศอินโดนีเซีย',
       'สาธารณรัฐแห่งสหภาพเมียนมาร์', 'ประเทศนิวซีแลนด์',
       'สาธารณัฐเกาหลีใต้', 'สาธารณรัฐมาเลเซีย', 'เมือง sapporo',
       'สาธารณรัฐจิบูตี และสาธารณรัฐฝรั่งเศส', 'สาธารณรัฐอิสลามอิหร่าน',
       'สาธารณรัฐอินโดนีเซียและสาธารณรัฐสิงคโปร์',
       'ราชอาณาจักรสวีเดนNational Veterinary Institute (SV',
       'กรมอนามัย  กระทรวงสาธารณสุข  เวลา 10.00-16.00 น.',
       'หอศิลป์สมเด็จพระนางเจ้าสิริกิติ์ พระบรมราชินีนาถ ถ', 'USA',
       'ประเทศ ฝรั่งเศส',
       'สหพันธ์สาธารณรัฐเยอรมนี สาธารณรัฐฝรั่งเศส และสมาพั',
       'สาธารณรัฐฝรั่งเศส สาธา รณรัฐอิตาลี สมาพันธรัฐสวิส',
       'สาธารณรัฐฝรั่งเศส สาธารณรัฐอิตาลี สมาพันธรัฐสวิส',
       'ประเทศสาธารณรัฐประชาธิปไตยประชาชนลาว',
       'สาธาณรัฐประชาธิปไตยประชาชนลาว', 'DATA NOT FOUND',
       'สาธารณรัฐประชาชนธิปไตยประชาชนลาว',
       'สาธารณรับประชาธิปไตยประชาชนลาว', 'เกาหลีเหนือ', 'นิวส์ซีแลนด์',
       'ซาอุดีอาระเบีย', 'จีน-ไต้หวัน', 'เอกวาดอร์', 'บรูไนดารุสซาลาม',
       'สาธารณรัฐสโลวัก และเดนมาร์ก', 'เบลเยี่ยมและเนเธอร์แลนด์',
       'สโลวาเกีย', 'สาธารณรัฐเกาหลี (เกาหลีใต้)', 'โปรตุเกต',
       'ไอซ์แลนด์', 'สาธารณรัฐแห่งสหภาพพม่า', 'สาธารณรัฐเช็ก',
       'สาธารณรัฐลิทัวเนีย', 'ราชอาณาจักรเนปาล', 'สาธารณรัฐเวียดนาม',
       'ิอินเดีย', 'สาธารณรัฐไอซ์แลนด์/สหราชอาณาจักร',
       'สหพันธ์สาธารณรัฐประชาธิปไตยเนปาล', 'สาธารณรัฐเช็ค',
       'สาธารณรัฐแอฟริกาใต้', 'ราชอาณาจักรเดนมาร์ก', 'สาธารณรัฐฟินแลนด์',
       'ณ เมืองบาหลี ประเทศอินโดนีเซีย',
       'สาธารณรัฐประชาธิปไตยประชาชนลาว และสาธารณรัฐสังคมนิ', 'Greece',
       'สหพันธ์สาธารณรัฐบราซิล', 'เมือง Vancouver  แคนาดา',
       'สาธารณรัฐเซอร์เบีย', 'ประเทศสเปน',
       'ลาว เวียดนาม จีนตอนใต้ และกัมพูชา', 'สาธาณรัฐประชาชนลาว',
       'สหราชอาณาจ้กร', 'สหพันธ์สาธารณรัฐเยอรมนีและออสเตรเลีย',
       'สาธาณรัฐรัสเซีย', 'ดูไบร์', 'Indonesia', 'ประเทศฝรั่งเศษ',
       'ประเทศฝรั่งเศส', 'สหภาพเมีนม่าร์', 'สิงคโปร์และมาเลเซีย',
       'ราชอาณาจักรไย', 'สาธารณรัฐสโลวีเนีย', 'สาธารณรัฐมาซิโดเนีย',
       'สาธารณรัฐเคนยา', 'ใต้หวัน', 'เยอรมณี',
       'รัฐอิสราเอล จอร์แดน คูเวต', 'ราชอาณาจักรไทย', 'ู',
       'ราชอาณาจักรกัมพูชาและสาธารณรัฐสังคมนิยมเวียดนาม',
       'สาธารณรัฐประชาธิปไตยประชาชนเกาหลี',
       'สาธารณรัฐสังคมนิยมประชาธิปไตยศรีลังกา', 'ราชอาณาจักรไทร',
       'สาธารณรัฐโปแลนด์', 'ราชอาณาจักรโมร็อกโก', 'ลาวและกัมพูชา',
       'สหราชอาณาจักรอังกฤษ',
       'ราชอาณาจักรเบลเยียม เนเธอร์แลนด์ ลักเซมเบิร์ก', 'ไอร์แลนด์[# 5]',
       'สวิตเซอร์แลนด์  อิตาลี', 'รัฐอิสราเอล',
       'สาธารณรัฐประชาธิปไตยประชาชนแอลจีเรีย', 'สหราชอาณาจักร(อังกฤษ)',
       'สหราชอาณาจักรบ', 'ราชอาณาจักรเบลเยียม',
       'สมาพันธรัฐสวิสเซอร์ และ สหพันธ์สาธารณรัฐเยอรมนี', 'Taiwan',
       'สาธารณรัฐบัลแกเรีย', 'กรุงเทพ', 'ป่ารีส', 'รัฐสุลต่านโอมาน',
       'ต่างประเทศ', 'เครือรัฐออสเตรเลีย/นิวซีแลนด์', 'นอร์เวย์/สวีเดน',
       'ราชอาณาจักรสวาซิแลนด์', 'เยอรมัน เนเธอร์แลนด์ เบลเยี่ยม',
       'สาธารณรัฐประชาธิปไตยติมอร์-เลสเต', 'สาธารณรัฐสหภาพพม่า',
       'สาธารณรัฐฮังการี', 'ไ้ต้หวัน', 'South Africa',
       'สาธารณรัฐไอซ์แลนด์', 'สาธารณรัฐฝรั่งเศส/สหราชอาณาจักร',
       'สาธารณรัฐเฮลเลนิก', 'ราชอาณาจักรนอร์เวย์และราชอาณาจักรสวีเดน',
       'สาธารณรัฐอาหรับอียิปต์ และตุรกี', 'ฮ่องกงสาธารณรัฐประชาชนจีน',
       'สาธาณรัฐตุรกี', 'รัฐกาตาร์', 'สาธารณรัฐสิงคโปร์/มาเลเซีย',
       'สาธารณรัฐสังคมนิยมเวียดนาม และสาธารณรัฐประชาธิปไตย',
       'เขตปกครองพิเศษฮ่องกง', 'สหพันธ์สาธารณรัฐประชาธิปไตยเอธิโอเปีย',
       'อบรม', 'เยอรมนี /ฝรั่งเศส/สหพันธรัฐสวิส',
       'สาธารณรัฐประชาชนบังกลาเทศ', 'สาธารณรัฐสิงคโปร์/มาเลเวีย', 'Macau',
       'สาธารณรัฐอินโดนีเซีย/เวียดนาม', 'สถานที่  ณ  ประเทศสิงคโปร์',
       'สาธารณรัฐประชาธิปไตยประชาชนลาว สาธารณรัฐสังคมนิยมเ',
       'ประเทศสิงคโปร์', 'สาธารณรัฐประชาธิปไตยประชาชนลาว/พม่า',
       'ประเทศสหรัฐอาหรับเอมิเรตส์', 'สหรััฐอเมริกา', 'Czech  Republic',
       'เยอรมันและเนเธอร์แลนด์', 'สาธารณรัฐคาซัคสถาน และสาธารณรัฐตุรกี',
       'สาธารณรัฐประชาชนจีน และฮ่องกง', 'ประเทศไทย',
       'สาธารัฐประชาธิปไตยประชาชนลาว', 'ประเทศสหรัฐอเมริกา',
       'ออสสเตรเลีย', 'ราชอาณาจักร',
       'อาณาจักรเนเธอร์แลนด์และสหรัฐอเมริกา', 'Belgium', 'เบลเยียม',
       'สาธารณรัฐรัสเซีย', 'เวียดนาม และลาว', 'บูรไน', 'ฺเบลเยี่ยม',
       'เยอรมัน และ สวิสเซอร์แลนด์', 'สาธารณรัฐประชาธิปไตยประชาชนจีน',
       'จีน/ญี่ปุ่น/พม่า/ฟิลิปปินส์', 'สาธารณรัฐแห่งสหภาพเมียนมา',
       'สโลวีเนีย', 'สก๊อตแลนด์', 'ฟิจิ', 'อิหร่าน', 'สาะารณรับเกาหลี',
       'ฝรังเศส', 'บัลแกเรีย', 'ไท', 'wmp', 'สหพันธรัฐเยอรมนี',
       'สาธารณประชาชนจีน', 'ประชุม', 'ประเทศเวียตนาม', 'อเมริกา',
       'โรงแรมเจริญธานีปริ๊นเซ็ส  จังหวัดขอนแก่น', 'ขอนแก่น  ไทย',
       'รพ. ศรีนครินทร์  ม. ขอนแก่น', 'สาธารณรัฐสโลวัก', 'ไทย, มาเลเซีย',
       'ไทย และ มาเลเซีย', 'สาธารณัฐอิตาลี', 'ราชกาณาจักรกัมพูชา',
       'เยรอมนี', 'Mauritius', 'ประเทศ Turkey', '0',
       'สาธารรัฐอินโดนีเซีย', 'สหภาพเมียนมาร์',
       'กัมพูชา และสาธารณรัฐประชาธิปไตยประชาชนลาว', 'สาธารณรัฐอินโดเนีย',
       'สหภาพเมียนมา', 'ไทยและมาเลเซีย', 'สาธารณรัฐแห่งสภาพพม่า',
       'สาธารณรัฐเคนย่า', 'ณ หลวงพระบาง สาธารณรัฐประชาธิปไตยประชาชนลาว',
       'สาธารณรัฐอินโดนนีเซีย', 'สาธาธรณรัฐประชาชนจีน', 'china',
       'จีนและเยอรมันนี', 'นิวซีแลนด์และออสเตรเลีย', 'สปป ลาว',
       'รพ.ศิริราช   กรุงเทพฯ', 'ประเทศสหราชอาณาจักร', 'ประเทศอังกฤษ',
       'ิสิงคโปร์', 'เขตบริหารพิเศษฮ่องกง',
       'สาธารณรัฐสิงคโปร์และสหพันธรัฐมาเลเซีย', 'สามาพันธรัสสวิส',
       'สาธารณรัฐประธิปไตยประชาชนลาว', 'สาธารณรัฐประชาธิปไตรประชาชนลาว',
       'สาธารัฐประชาชนจีน', 'malasia',
       'สมาชิกเชงเกน (อิตาลี สวิสเซอร์แลนด์ ฝรั่งเศส และเน',
       'สหพันธรัฐมาเลเซีย', 'ชลบุรี', 'สมาพันธรัฐรัสเซีย', 'ประเทศเกาหลี',
       'สาธารณรัฐประชุาชนจีน', 'สหพันธรัฐมาเลเซียและสาธารณรัฐสิงคโปร์',
       'สาธารณรัฐโครเอเซีย', 'ราชอาราจักสเปน', 'ไซปรัส', 'ไตัหวัน',
       'ไทยเข้าร่วมโครงการ',
       'สาธารณรัฐสังคมนิยมเวียดนาม สาธารณรัฐสิงคโปร์ สหพัน',
       'สาธารัฐแอฟริกาใต้', 'ประเทศอิตาลี', 'เมียรม่า',
       'เวียดนามและกัมพชา', '์ ไทย', 'Thai', 'ุ',
       'ณ สาธารณรัฐลัตเวีย และสาธารณรัฐลิทัวเนีย',
       'สาธารณรัฐลัตเวีย และ สาธารณรัฐลิทัวเนีย', 'ประเทศกัมพูชา',
       'จอร์เจีย', 'สาธารณรัฐเมียนมา', 'สเปน และ อิตาลี',
       'สาธารณรัฐจีน(ไต้หวัน)', 'เวลส์', 'The Northern of Cyprus',
       'มาเลเซีย และ สิงคโปร์', 'อินโดนีเซีย และ เวียดนาม',
       'สาธารณรัฐสังคมนิยมเวียดนาน', 'สาธารณรัฐสโลวาเนีย',
       'ออสเตรเลีย และ มาเลเซีย', 'สาธารณรัฐเยอรมันนี',
       'สหราชอาณาจักร-บริเตนใหญ่และไอร์แลนด์เหนือ', 'สมาพันธรัฐสวิซ',
       'ลาว และ เวียดนาม',
       'ณ ห้องบรรยาย 201 ชั้น 2 อาคารศูนย์แพทยศาสตร์ศึกษาช',
       'สาธารณรัฐฟินแลน์', 'สหราช-อาณาจักร (United Kingdom)',
       'ประเทศโรมาเนีย', 'ขอนแก่น',
       'เขตบริหารพิเศษมาเก๊าแห่งสาธารณรัฐประชาชนจีน',
       'ราชอาณาจักรเบลเยี่ยม', 'TAIWAN', 'สาธารณรัฐเยอรมณี', 'ญี่ปุ่่น',
       'สาธารรัฐประชาชนจีน', 'เบลเยียม และเนเธอร์แลนด์', '/ไทย',
       'เบลเยียม อังกฤษ เนเธอแลนด์', 'ญี่ปุ่น', 'สหภาพเมียมาร์',
       'ญี่ปุ่นและสหรัฐอเมริกา', 'แคนนาดา',
       'สิงคโปร์ มาเลเซีย และฟิลิปปินส์',
       'สิงคโปร์ ฟิลิปปินส์ และมาเลเซีย', 'Myanmar', 'ปาปัวนิวกินี',
       'สิงคโปร์ และมาเลเซีย', 'ไทบ', 'สหราชอาณาจักรและสาธารณรัฐฝรั่งเศส',
       'สิงคโปร์ เมียนมาร์ มาเลเซีย กัมพูชา', 'จีน เกาหลีใต้',
       'โครเอเชีย', 'สหราชอาณาจักร.', 'เวียดนาม.', 'ประเทศโปรตุเกส',
       'ประเทศญี่ปุ่น', 'ประเทศสาธารณรัฐโปรตุเกส', 'เนเธอแลนด์',
       'เบลเยียม เยอรมันนี', 'เบลเยียม นอร์เวย์',
       'เเบลเยี่ยม เยอรมันนี นอร์เวย์', 'สมพันธรัฐสวิส', 'ปารีส', 'สวิส',
       'สหพันธ์สาธารณรับเยอรมนี', 'ประเทศรัฐเซีย', 'Chaina',
       'ราชอาณาจักรกัมพุชา', 'ประชาธิปไตยประชาชนลาว', 'จึน',
       'ไต้หวัน และ จีน', 'เปรู', 'โปรแลนด์', 'สหรัฐอเมริกา และ แคนาดา',
       'โมร็อกโก', 'australia', 'UK', 'เบลเยียม,เยอรมนี', 'เมียนมา',
       'เซอร์เบีย', 'มอลตา,บัลแกเรีย', 'มาเลเซีย,สิงคโปร์',
       'เยอรมนีและออสเตรีย', 'ลัทเวีย', 'บรัสเซลล์ และ เบลเยี่ยม',
       'ลัตเวีย', '็ไทย', 'สหรราชอาณาจักร', 'ไอซ์แลนด์เหนือ',
       'ประเทศเดนมาร์ก', 'คอสตาริก้า', 'คอสตาริกา', 'ัไทย', 'Kazakhstan',
       'คาซัคสถาน', 'สาธารณรัฐเฮเลนิก', 'ไทย+',
       'สาธารณรัฐฝรั่งเศส และ สหพันธ์สาธารณรัฐเยอรมัน', 'บังกลาเทศ',
       'สาธารณรัฐประชาธิปไจยประชาชนลาว',
       'Czech Republic และสาธารณรัฐเยอรมนี', 'ประเทศตุรกี', 'ไท่ย',
       'เยอรมนี และเนเธอร์แลนด์', 'เนเธอร์แลนด์ และ ฝรั่งเศส',
       'ประเทศฮังการี', 'นอร์เวย์ และ สวิสเซอร์แลนด์', 'สาธารณรัฐชิลี',
       'แม็กซิโก', 'เนเธอร์แลนด์ และ เบลเยี่ยม',
       'เนเธอร์แลนด์ และเบลเยี่ยม', 'ยูกันดา', 'สก็อตแลนด์',
       'ทรานส์นิสเตรีย',
       'ห้องประชุม Crystal Ballroom โรงแรมตวันนา กรุงเทพ',
       'ณ  คณะสาธารณสุขศาสตร์  มหาวิทยาลัยขอนแก่น',
       'ห้องประชุม ๘๐๙ ราชวิทยาลัยสูติฯ ชั้น ๘ อาคารเฉลิมพ',
       'ณ   โรงแรมรามาการ์เดนส์   กรุงเทพฯ',
       'โรงแรมรามาการ์เดนส์   กรุงเทพฯ', 'สาธารณรัฐโครเอเชีย',
       'สาธารณรัฐสหภาพเมียนมา', 'อาเจนติน่า', 'กานา',
       'สาธารณรัฐเช็ก และ เนเธอร์แลนด์', 'อาเซอร์ไบจาน',
       'สิงคโปร์ และ อินโดนีเซีย', 'ณ โรงแรม The Athenee Hotel กรุงเทพฯ',
       'กรีซและเนเธอร์แลนด์', 'สาธารณรัฐจีน (ไต้หวัน)', 'กทม',
       'เยอรมนี ออสเตรีย และสวิตเซอร์แลนด์', 'อุซเบกิสถาน',
       'สวีเดน และ เอสโตรเนีย', 'ญี่ปุ่น และ เกาหลีใต้',
       'ประเทศสาธารณรัฐแห่งสหภาพเมียนมา', 'กัมพูชา และ ฟิลิปปินส์',
       'เดนมาร์ก และ สหราชอาณาจักร', 'อินโดนีเซีย และติมอร์เลสเต', 'ไท0',
       'สาธารณรัฐสหภาพเมียนมาร์', 'ไทน', 'ราชอาณาจักรฮัชไมต์จอร์แดน',
       'เยอรมนี และ ฝรั่งเศส', 'เยอรมันนี และ ฝรั่งเศส',
       'เกาหลีใต้,ไต้หวัน', 'สาธารณัฐเกาหลี (เกาหลีใต้)',
       'เกาหลีใต้ และ ไต้หวัน', 'ประเทศ Czeech Republic',
       'Dubrovnik สาธารณรัฐโครอเชีย', 'ประเทศสิงค์โปร', 'czech republic',
       'เมือง Athens ประเทศ Greece', 'ออสเตเรีย',
       'เมืองโฮจีมินทร์ ประเทศเวียดนาม', '-', 'งบนอกเหนืองบประชุมวิชาการ',
       '้ไทย', 'ไืน', 'ราชอาณาจักรสกอตแลนด์', 'Malaysia', 'ออสเตรีย(ไทย)',
       'Mumbai India', 'ไทย์', '์ไทย', 'online', 'สราชอาณาจักร',
       'มหาวิทยาลัยมหิดล', 'ไทย / สหรัฐอเมริกา',
       'สวิตเซอร์แลนด์,นอร์เวย์', 'โรงสีข้าวพระราชทาน น่าน', 'ไ่ทย',
       'ิไทย', 'สาธารณรัฐเปรู', 'ฝรั่งเศสและสเปน', 'ไทยข',
       'สหราชอาณาจักรบริเตนใหญ่ และไอร์แลนด์เหนือ',
       'สหราชอาณาจักรสกอตแลด์', 'ฟินแลนด์ และ สาธารณรัฐเอสโตเนีย',
       'ปารากวัย', 'ฝรั่งเศส และ สหราชอาณาจักร', 'Sunstun makeup-studio',
       'สาธารณรัฐเฮลเลนิก (กรีซ)',
       'สมาพันธรัฐสวิสและสหพันธ์สาธารณรัฐเยอรมนี', 'Thailand',
       'ออสเตรเลีย และนิวซีแลนด์', 'เอสโตเนีย', 'สำนักงานอธิการบดี',
       'ห้องประชุมสำนักงาน คณะเทคนิคการแพทย์', 'คณะเทคนิคการแพทย์',
       'จังหวัดระยอง', 'ราชอาณาจักรเบลเยี่ยม และ สหพันธ์สาธารณรัฐเยอรมนี',
       'สหราชอาณาจักร และ เยอรมนี', 'ญี่ปุน',
       'บอสเนียและเฮอร์เซโกวีนา และ ฮังการี', 'มาเลเซีย และ สิงค์โปร์',
       'สาธารณรัฐสังคมนิยมประชาธิปไตยศรีลังกา กรุงเทพมหานค',
       'เนการาบรูไนดารุสซาลาม',
       'สาธารณรัฐประชาชนจีน และ สาธารณรัฐประชาธิปไตยประชาช',
       'สาธารณรัฐเกาหลี (เกาหลีใต้) และ ญี่ปุ่น',
       'สาธารณรัฐประชาธิปไตยชาชนลาว',
       'ราชอาณาจักรสวีเดน สาธารณรัฐเอสโตเนียและสาธารณรัฐฟิ',
       'สาธารณรัฐประชาธิปไตยติมอร์ - เลสเต',
       'ราชอาณาจักรสวีเดน เอสโตเนีย และฟินแลนด์', 'สาธารณรัฐคาซัคสถาน',
       'end', '                     '], dtype=object)

In [130]:
correction_dict = {'ประเทศสิงค์โปร์บริษัท เฮ็ลธ อินโนเวณัน จำกัด': 'สิงคโปร์','เกาหลีใต้ใต้ใต้ และ ไต้หวัน': 'เกาหลีใต้และไต้หวัน', ' Czeech Republic': 'กรีซ',
       'Dubrovnik สาธารณรัฐโครอเชีย': 'โครเอเชีย', 'สิงค์โปร': 'สิงคโปร์','เมือง Athens  Greece': 'กรีซ',
       'ออสเตเรีย': 'ออสเตรีย','เมืองโฮจีมินทร์ เวียดนาม': 'เวียดนาม',
       'งบนอกเหนืองบวิชาการ': 'ไทย', 'ราชอาณาจักรสกอตแลนด์':'สกอตแลนด์', 'Malaysia': 'มาเลเซีย','สหพันธ์สาธารณรัฐประชาธิปไตยเนปาล':'เนปาล','ลาว และสาธารณรัฐสังคมนิ':'ลาวและเวียดนาม',
                   'ณ เมืองบาหลี อินโดนีเซีย':'อินโดนีเซีย','Greece':'กรีซ','สหพันธ์สาธารณรัฐบราซิล':'บลาซิล',
'เมือง Vancouver  แคนาดา':'แคนาดา','ลาว เวียดนาม จีนตอนใต้ และกัมพูชา':'ลาว เวียดนาม จีนและกัมพูชา','สาธาณรัฐประชาชนลาว':'ลาว','ดูไบร์':'ดูไบ','Indonesia':'อินโดนีเซีย',
'สหภาพเมีนม่าร์':'พม่า','ราชอาณาจักรไย':'ไทย','เยอรมณี':'เยอรมนี','ราชอาณาจักรไทย':'ไทย','ราชอาณาจักรกัมพูชาและสาธารณรัฐสังคมนิยมเวียดนาม':'กัมพูชาและเวียดนาม','สาธารณรัฐประชาธิปไตยประชาชนเกาหลีใต้ใต้':'เกาหลีใต้',
'สาธารณรัฐสังคมนิยมประชาธิปไตยศรีลังกา':'ศรีลังกา','ราชอาณาจักรไทร':'ไทย','สหราชอาณาจักรอังกฤษ':'สหราชอาณาจักร','สาธารณรัฐฝรั่งเศส สาธา รณรัฐอิตาลี สมาพันธรัฐสวิส':'ฝรั่งเศส อิตาลี สวิตเซอร์แลนด์',
'สาธาณรัฐประชาธิปไตยประชาชนลาว':'ลาว','สาธารณรัฐประชาชนธิปไตยประชาชนลาว':'ลาว','สาธารณรับประชาธิปไตยประชาชนลาว':'ลาว','เกาหลีใต้ใต้เหนือ':'เกาหลีใต้',
'นิวส์ซีแลนด์':'นิวซีแลนด์','บรูไนดารุสซาลาม':'บรูไน','สาธารณรัฐสโลวัก และเดนมาร์ก':'สาธารณรัฐสโลวักและเดนมาร์ก','เกาหลีใต้ใต้ใต้ (เกาหลีใต้ใต้ใต้)':'เกาหลีใต้ใต้','สาธารณรัฐเวียดนาม':'เวียดนาม','สาธารณรัญอินเดีย':'อินเดีย',
'vietnam':'เวียดนาม','สาธารณรัฐอินเดีย':'อินเดีย','สาธารรัณสังคมนิยมเวียดนาม':'เวียดนาม','สาธารรัณสังคมนิยมเวียดนาม':'เวียดนาม','South เกาหลีใต้ใต้ใต้':'เกาหลีใต้',
'สาธารณรัฐแห่งพม่า':'พม่า','กรมอนามัย  กระทรวงสาธารณสุข  เวลา 1.-16. น.':'ไทย','สาธารณัฐเกาหลีใต้ใต้ใต้':'เกาหลีใต้','สาธารณรัฐฟิลิปปินส์':'ฟิลิปปินส์',
'สาธารณรัฐมาเลเซีย':'มาเลเซีย','เมือง sapporo':'ญี่ปุ่น','สาธารณรัฐจิบูตี และสาธารณรัฐฝรั่งเศส':'สาธารณรัฐจิบูตีและฝรั่งเศส','สวีเดนNational Veterinary Institute (SV':'สวีเดน',
'หอศิลป์สมเด็จพระนางเจ้าสิริกิติ์ พระบรมราชินีนาถ ถ':'ไทย','USA':'สหรัฐอเมริกา','สาธารณรัฐอินโดนีเซียและสาธารณรัฐสิงคโปร์':'อินโดนีเซียและสิงคโปร์','สิงค์โปร์':'สิงคโปร์','ราชอาณาจักรสวีเดน':'สวีเดน','สาธารณรัฐคาซัคสถาน':'คาซัคสถาน','สาธารณรัฐประชาธิปไตยติมอร์':'ติมอร์-เลสเต',
'สาธารณรัฐเกาหลี':'เกาหลีใต้','สาธารณรัฐเกาหลีใต้':'เกาหลีใต้','สาธารณรัฐประชาธิปไตยชาชนลาว':'ลาว','ราชอาณาจักรสวีเดน สาธารณรัฐเอสโตเนียและสาธารณรัฐฟิ':'สวีเดน เอสโตเนียและฟิลิปปินส์',
'สาธารณรัฐประชาชนจีน และ สาธารณรัฐประชาธิปไตยประชาช':'จีนและลาว','สาธารณรัฐเกาหลี (เกาหลีใต้) และ ญี่ปุ่น':'เกาหลีใต้และญี่ปุ่น','สาธารณรัฐเกาหลีใต้และญี่ปุ่น':'เกาหลีใต้และญี่ปุ่น',
'ไทย+':'ไทย', '็ไทย':'ไทย','Lao':'ลาว','เยอรมมนี':'เยอรมนี','สาธารณรัฐประชาธิปไตยประชาชาลาว':'ลาว','สาธารณรัฐสังคมนิมเวียดนาม':'เวียดนาม','ไต้หวันศธ0514.26....1.1/467  ลว. 15 .ก.พ.55':'ไต้หวัน',
 'Italy':'อิตาลี','Korea':'เกาหลีใต้','ห้องประุมสมาคมศิษย์เก่า เวลา 12.00-13.00 น':'ไทย','ราชอาณาจักรกัมพูชาทุน':'กัมพูชา', 'มาเลเซีย  และสิงคโปร์':'มาเลเซียและสิงคโปร์',
 'Turkey':'ตุรกี','Brunei':'บรูไน','สาธารณรัฐส้งคโปร์':'สิงคโปร์','ห้องนพดล ทองโสภิต':'ไทย','สาธารณรัญอินเดีย':'อินเดีย','Germany':'เยอรมนี','อังกฤษ/ฝรั่งเศล':'อังกฤษ/ฝรั่งเศส','Singapore':'สิงคโปร์',
'Spain':'สเปน','Micronesia':'ไมโครนีเชีย','Haiti':'เฮติ','ใต้หวัน':'ไต้หวัน','ห้องจำลอง   มุ่งการดี ชั้น 4  อาคารสมเด็จพระ':'ไทย',
'ไืทย':'ไทย','อิตา':'อิตาลี','ฝรั่งเศษ':'ฝรั่งเศส','เกาหลีใต้ใต้และจีน':'เกาหลีใต้และจีน','ฮ่องกงและเกาหลีใต้ใต้ใต้':'ฮ่องกงและเกาหลีใต้',
'สิบสองปันนาจีน':'จีน','สาธารณรัฐไต้หวัน':'ไต้หวัน','ตุรกรี':'ตุรกี','ไ':'ไทย','สปน':'สเปน','CHINA':'จีน',
'ไิทย':'ไทย','Malta':'มอลตา','สิงคโปร์บริษัท เฮ็ลธ อินโนเวณัน จำกัด':'สิงคโปร์','เวียนามและจีน':'เวียดนามและจีน','เกาหลีใต้ใต้และฮ่องกง':'เกาหลีใต้และฮ่องกง',
'พม่า  จีน':'พม่า จีน','Lithuania':'ลิทัวเนีย','ลิธัวเนีย':'ลิทัวเนีย','ราชอาณาจักรกัมพูชา':'กัมพูชา','สาธารณัฐประชาธิปไตยประชาชนลาว':'ลาว','สวิตเซอร์แลนด์ และ อิตาลี':'สวิตเซอร์แลนด์และอิตาลี',
                    'สหพันธรัฐรัสเซีย':'รัสเซีย', 'ไืทยในส่วนราชการ':'ไทย','ออสเตรเลียและเชค':'ออสเตรเลียและสาธารณรัฐเช็ก','seychelles':'สาธารณรัฐเซเชลส์',
 'โมร็อกโค':'โมร็อกโก', 'เยอรมนี,ฝรั่งเศส,อังกฤษ':'เยอรมนี,ฝรั่งเศส,สหราชอาณาจักร','ไต้หวัน1':'ไต้หวัน', 'ไำทย':'ไทย',
 'ไทย.':'ไทย','Switzerland และ  อิตาลี':'สวิตเซอร์แลนด์และอิตาลี','สาะรณรัฐประชาธิปไตยประชาชนลาว':'ลาว', 'เขตบริหารพิเศษฮ่องกงแห่งสาธารณรัฐประชาชนจีน':'ฮ่องกง',
  'ฮ่องกง สาธารณับประชาชนขจีน':'ฮ่องกง','เกาหลี':'เกาหลีใต้', 'สาธารณรัฐประชาธิปไตยประชาชนลาว':'ลาว','เบลเยี่ยม':'เบลเยียม',
   'สวิสเซอร์แลนด์':'สวิตเซอร์แลนด์', 'สาธารณรัฐเชค':'สาธารณรัฐเช็ก','เชคโกสโลวาเกีย':'เชโกสโลวาเกีย','สาธารณรัฐประชาชนจีน':'จีน',
    'เมียนมาร์':'พม่า', 'สาธารณรัฐออสเตรีย':'ออสเตรีย', 'โปร์แลนด์':'โปแลนด์','เดนมาร์ค':'เดนมาร์ก', 'โครเอเซีย':'โครเอเชีย','สหราชอาณาจักรบริเตนใหญ่และไอร์แลนด์เหนือ':'สหราชอาณาจักร',
    'โมนาโค':'โมนาโก', 'สาธารณรัฐอิตาลี':'อิตาลี', 'เยอรมนีนี':'เยอรมนี', 'สหพันธ์สาธารณรัฐเยอรมนี':'เยอรมนี','czech republic':'สาธารณรัฐเช็ก','อัฟริกาใต้':'แอฟริกาใต้', 'สหภาพพม่า':'พม่า',
    'สาธารณรัฐอิสลามปากีสถาน':'ปากีสถาน','United Arab Emirates':'สหรัฐอาหรับเอมิเรตส์','อ่องกง':'ฮ่องกง','สาธารณรัญอินเดีย':'อินเดีย','สมาพันธรัฐสวิส':'สวิตเซอร์แลนด์','เครือรัฐออสเตรเลีย':'ออสเตรเลีย',
'สาธารณรัฐอินโดนีเซีย':'อินโดนีเซีย','Saudi Arabia':'ซาอุดีอาระเบีย','Austria':'ออสเตรีย','สาธารณรัฐสิงคโปร์':'สิงคโปร์',
'Burkina Faso':'บูร์กินาฟาโซ','สหพันธรัฐสวิส':'สวิตเซอร์แลนด์','สาธารณรัฐสังคมนิยมเวียดนาม':'เวียดนาม','สาธารณรัฐจีน':'จีน',
'ลาว ลาว และ เวียดนาม':'ลาวและเวียดนาม','สปป.ลาว':'ลาว','ใน':'ไทย','จีน (ใต้หวัน)':'ไต้หวัน','สวิตเซอร์แลนด์ และฝรั่งเศส':'สวิตเซอร์แลนด์และฝรั่งเศส',
'กรุงเทพฯ':'ไทย','Australia':'ออสเตรเลีย','England':'สหราชอาณาจักร','มาดากัสการ์โมซัมบิก และแอฟริกาใต้':'มาดากัสการ์โมซัมบิกและแอฟริกาใต้',
'ราชอาณาจักรเนเธอแลนด์':'ราชอาณาจักรเนเธอร์แลนด์','Japan':'ญี่ปุ่น','ราชอานาจักรกัมพูชา':'กัมพูชา','Hong Kong':'ฮ่องกง','เยอรมันนี':'เยอรมนี',
'Czech Republic':'สาธารณรัฐเช็ก','มัลดีฟล์':'มัลดีฟส์','บังคลาเทศ':'บังกลาเทศ','ควีนส์แลนด์':'ออสเตรเลีย','สาธารณรัฐอาหรับอียิปต์':'อียิปต์',
'สาธารณรัฐโปรตุเกส':'โปรตุเกส','สาธารณรัฐอาหรับเอมิเรสต์':'สหรัฐอาหรับเอมิเรสส์','Beigium':'เบลเยียม','สหพันธ์สาธารณรัฐเยอมณี':'เยอรมณี',
'นอกคณะ':'ไทย','ในคณะ':'ไทย','เกาหลีใต้ใต้ใต้ใต้':'เกาหลีใต้','สหรัฐสหรัฐสหรัฐอเมริกา':'สหรัฐอเมริกา','เกาหลีใต้ใต้ใต้':'เกาหลีใต้ใต้',
'เกาหลีใต้ใต้':'เกาหลีใต้','อเมริกกา':'สหรัฐอเมริกา','มหาวิทยาลัยมหิดล':'ไทย','ไทย / สหรัฐอเมริกา':'ไทย/สหรัฐอเมริกา','ไทยข':'ไทย',
'สหราชอาณาจักรบริเตนใหญ่ และไอร์แลนด์เหนือ':'สหราชอาณาจักรบริเตนใหญ่และไอร์แลนด์','สหราชอาณาจักรสกอตแลด์':'ราชอาณาจักรสกอตแลด์',
'โรงสีข้าวพระราชทาน น่าน':'ไทย','ห้องประชุมสำนักงาน คณะเทคนิคการแพทย์':'ไทย','คณะเทคนิคการแพทย์':'ไทย','สหราชอาณาจักร และ เยอรมนี':'สหราชอาณาจักรและเยอรมนี',
'เกาหลีใต้ใต้ (เกาหลีใต้ใต้) และ ญี่ปุ่น':'เกาหลีใต้และญี่ปุ่น','Sunstun makeup-studio':'ไทย','สวีเดน เอสโตเนีย และฟินแลนด์':'สวีเดน เอสโตเนียและฟินแลนด์',
'เยอรมนี และเนเธอร์แลนด์':'เยอรมนีและเนเธอร์แลนด์','ณ  คณะสาธารณสุขศาสตร์  มหาวิทยาลัยขอนแก่น':'ไทย','ห้องประชุม Crystal Ballroom โรงแรมตวันนา กรุงเทพ':'ไทย',
'ทรานส์นิสเตรี':'ทรานส์นีสเตรีย','ไืน':'ไทย','ไท0':'ไทย','กทม':'ไทย','เยอรมันนี และ ฝรั่งเศส':'เยอรมนีและฝรั่งเศส','ห้องประชุม ๘๐๙ ราชวิทยาลัยสูติฯ ชั้น ๘ อาคารเฉลิมพ':'ไทย',
'ณ โรงแรม The Athenee Hotel กรุงเทพฯ':'ไทย','สวีเดน และ เอสโตรเนี':'สวีเดนและเอสโตเนีย','สาธารณประชาชนจีน':'จีน','อเมริกา':'สหรัฐอเมริกา','โรงแรมเจริญธานีปริ๊นเซ็ส  จังหวัดขอนแก่น':'ไทย','ขอนแก่น  ไทย':'ไทย','รพ. ศรีนครินทร์  ม. ขอนแก่น':'ไทย','ไทย, มาเลเซีย':'ไทย,มาเลเซีย',
'ไทย และ มาเลเซีย':'ไทยและมาเลเซีย','สาธารณัฐอิตาลี':'อิตาลี','ราชกาณาจักรกัมพูชา':'กัมพูชา','เยรอมนี':'เยอรมนี','Mauritius':'สาธารณรัฐมอริเชียส',
' ตุรกี':'ตุรกี','ณ ห้องบรรยาย 21 ชั้น 2 อาคารศูนย์แพทยศาสตร์ศึกษาช':'ไทย','สาธารณรัฐฟินแลน์':'สาธารณรัฐฟินแลนด์',
'สหราช-อาณาจักร (United Kingdom)':'สหราชอาณาจักร','ขอนแก่น':'ไทย','เขตบริหารพิเศษมาเก๊าแห่งจีน':'มาเก๊า','TAIWAN':'ไต้หวัน',
'สาธารณรัฐเยอรมณี':'เยอรมณี','สาธารรัฐประชาชนจีน':'จีน','ญี่ปุ่่น':'ญี่ปุ่น','/ไทย':'ไทย','สหภาพเมียมาร์':'พม่า','Myanmar':'พม่า', 'เมียนมา':'พม่า', 'บรัสเซลล์ และ เบลเยียม':'บรัสเซลล์และเบลเยียม','สหรราชอาณาจักร':'สหราชอาณาจักร',
 'ไอซ์แลนด์เหนือ':'ไอซ์แลนด์','คอสตาริก้า':'คอสตาริกา','Kazakhstan':'คาซัคสถาน',
 'สาธารณรัฐประชาธิปไจยประชาชนลาว':'ลาว','Czech Republic และสาธารณรัฐเยอรมนี':'เช็กเกียและเยอรมนี','เนเธอร์แลนด์ และ ฝรั่งเศส':'เนเธอร์แลนด์และฝรั่งเศส',
 'ณ   โรงแรมรามาการ์เดนส์   กรุงเทพฯ':'ไทย','โรงแรมรามาการ์เดนส์   กรุงเทพฯ':'ไทย','สาธารณรัฐสหภาพเมียนมา':'พม่า','สาธารณรัฐเช็ก และ เนเธอร์แลนด์':'สาธารณรัฐเช็กและเนเธอร์แลนด์',
 'สิงคโปร์ และ อินโดนีเซีย':'สิงคโปร์และอินโดนีเซีย','สาธารณรัฐจีน (ไต้หวัน)':'ไต้หวัน'}

In [82]:
def correct_spelling(word, correction_dict):
    return correction_dict.get(word, word)

In [83]:
df['ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ'] = df['ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ'].apply(lambda x: correct_spelling(x, correction_dict))

In [74]:
print("ข้อมูลหลังทำความสะอาด:")
print(df)

ข้อมูลหลังทำความสะอาด:
       Unnamed: 0 Unnamed: 1            Unnamed: 2  \
0              id   sequence       statuslist-อ้อม
1          100008          2  ฝึกอบรม ณ ต่างประเทศ
2          100008          3       ลาศึกษาในประเทศ
3          100008          4  ลาศึกษา ณ ต่างประเทศ
4          100009          5  ลาศึกษา ณ ต่างประเทศ
...           ...        ...                   ...
230063        NaN        NaN                   NaN
230064        NaN        NaN                   NaN
230065        NaN        NaN                   NaN
230066        NaN        NaN                   NaN
230067        NaN        NaN                   NaN

       ดูข้อมูลจาก ประเภทการลาศึกษา ชีต LoVs           Unnamed: 4  \
0                                ประเภทการลา              details
1                     ไปฝึกอบรม ณ ต่างประเทศ          ภาษาญี่ปุ่น
2                            ลาศึกษาในประเทศ     วิชาญี่ปุ่นศึกษา
3                       ลาศึกษา ณ ต่างประเทศ          ภาษาญี่ปุ่น
4                       ลาศึกษา ณ ต่างประเทศ  Operative Dentistry
...                                      ...                  ...
230063                                   NaN                  NaN
230064                                   NaN                  NaN
230065                                   NaN                  NaN
230066                                   NaN                  NaN
230067                                   NaN                  NaN

               Unnamed: 5 Unnamed: 6  Unnamed: 7  Unnamed: 8  \
0       studylevel-ลิเดีย     Reason        sday        eday
1                     NaN        NaN  1995-09-25  1996-07-09
2                ปริญญาโท   ปริญญาโท  1999-07-01  2001-06-30
3                ปริญญาโท        NaN  2001-03-31  2002-03-30
4            ปริญญาโท-เอก        NaN  1997-04-25  2002-10-24
...                   ...        ...         ...         ...
230063                NaN        NaN         NaN         NaN
230064                NaN        NaN         NaN         NaN
230065                NaN        NaN         NaN         NaN
230066                NaN        NaN         NaN         NaN
230067                NaN        NaN         NaN         NaN

                                          Unnamed: 9  \
0                                          place-เตย
1       Japan Foundation Japanese-Language Institute
2                              มหาวิทยาลัยธรรมศาสตร์
3                                    Keio University
4                                 Indiana University
...                                              ...
230063
230064                                           NaN
230065                                           NaN
230066                                           NaN
230067                                           NaN

                                         Unnamed: 10  \
0                                           location
1       Japan Foundation Japanese-Language Institute
2                              มหาวิทยาลัยธรรมศาสตร์
3                                    Keio University
4                                 Indiana University
...                                              ...
230063                                           NaN
230064                                           NaN
230065                                           NaN
230066                                           NaN
230067                                           NaN

       ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ   Unnamed: 12  \
0                                country-แอน       country
1                                     แคนาดา       ญี่ปุ่น
2                                        ไทย           ไทย
3                                    ญี่ปุ่น       ญี่ปุ่น
4                               สหรัฐอเมริกา  สหรัฐอเมริกา
...                                      ...           ...
230063                                   NaN           NaN
230064                                   NaN           NaN
230065                                   NaN           NaN
230066                                   NaN           NaN
230067                                                 NaN

                                              Unnamed: 13  \
0                                             scholarship
1       The Japan Foundation Japanese Language Insititute
2                                                 ส่วนตัว
3                    Keio University Graduate Scholarship
4                                รัฐบาล (ทบวงมหาวิทยาลัย)
...                                                   ...
230063                                                NaN
230064                                                NaN
230065                                                NaN
230066                                                NaN
230067                                                NaN

                     Unnamed: 14
0                      reference
1         มข.3023/38  ลว.8ก.ย.38
2         มข.1889/42 ลว.2 ก.ค.42
3       มข.1479/44 ลว.20 มิ.ย.44
4        มข.1640/40 ลว.16 พ.ค.40
...                          ...
230063                       NaN
230064                       NaN
230065                       NaN
230066                       NaN
230067                       NaN

[230068 rows x 15 columns]

In [ ]:
import numpy as np

In [ ]:
arr = np.array(['nan'], dtype=object)

In [ ]:
arr = np.where(arr == 'nan', np.nan, arr)

In [ ]:
print(arr)

[nan]

In [ ]:
arr

array([nan], dtype=object)

In [7]:
df['ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ'] = df['ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ'].astype(str) #เปลี่ยนค่าให้เป็นstr

In [ ]:


     , 'เยอรมนี ออสเตรีย และสวิตเซอร์แลนด์',
       'อุซเบกิสถาน', 'สวีเดนและเอสโตเนียย',
       'ญี่ปุ่น และ เกาหลีใต้ใต้ใต้', 'กัมพูชา และ ฟิลิปปินส์',
       'เดนมาร์ก และ สหราชอาณาจักร', 'อินโดนีเซีย และติมอร์เลสเต', 'ไทน',
       'ราชอาณาจักรฮัชไมต์จอร์แดน', 'เยอรมนี และ ฝรั่งเศส',
       'เยอรมนีและฝรั่งเศส', 'เกาหลีใต้ใต้ใต้,ไต้หวัน',
       'สาธารณัฐเกาหลีใต้ใต้ (เกาหลีใต้ใต้ใต้)',

In [ ]:
 'สาธารณรัฐเยอรมันนี', 'สหราชอาณาจักร-บริเตนใหญ่และไอร์แลนด์เหนือ',
       'สมาพันธรัฐสวิซ', 'ลาว และ เวียดนาม', 'มาเก๊า', 'ญี่ปุ่น',
       'เบลเยียม และเนเธอร์แลนด์', 'เบลเยียม อังกฤษ เนเธอแลนด์',
       'ญี่ปุ่นและสหรัฐสหรัฐสหรัฐอเมริกา', 'แคนนาดา',
       'สิงคโปร์ มาเลเซีย และฟิลิปปินส์',
       'สิงคโปร์ ฟิลิปปินส์ และมาเลเซีย', 'ปาปัวนิวกินี',
       'สิงคโปร์ และมาเลเซีย', 'ไทบ', 'สหราชอาณาจักรและสาธารณรัฐฝรั่งเศส',
       'สิงคโปร์ พม่า มาเลเซีย กัมพูชา', 'จีน เกาหลีใต้ใต้ใต้',
       'สหราชอาณาจักร.', 'เวียดนาม.', 'เนเธอแลนด์', 'เบลเยียม เยอรมันนี',
       'เบลเยียม นอร์เวย์', 'เเบลเยียม เยอรมันนี นอร์เวย์',
       'สมพันธรัฐสวิส', 'ปารีส', 'สวิส', 'สหพันธ์สาธารณรับเยอรมนี',
       'รัฐเซีย', 'Chaina', 'ราชอาณาจักรกัมพุชา', 'ประชาธิปไตยประชาชนลาว',
       'จึน', 'ไต้หวัน และ จีน', 'เปรู', 'โปรแลนด์',
       'สหรัฐสหรัฐสหรัฐอเมริกา และ แคนาดา', 'australia', 'UK',

In [ ]:
  'สาธารณรัฐสิงคโปร์และสหพันธรัฐมาเลเซีย', 'สามาพันธรัสสวิส',
       'สาธารณรัฐประธิปไตยประชาชนลาว', 'สาธารณรัฐประชาธิปไตรประชาชนลาว',
       'สาธารัฐประชาชนจีน', 'malasia',
       'สมาชิกเชงเกน (อิตาลี สวิตเซอร์แลนด์ ฝรั่งเศส และเน',
       'สหพันธรัฐมาเลเซีย', 'ชลบุรี', 'สมาพันธรัฐรัสเซีย',
       'สาธารณรัฐประชุาชนจีน', 'สหพันธรัฐมาเลเซียและสาธารณรัฐสิงคโปร์',
       'สาธารณรัฐโครเอเชีย', 'ราชอาราจักสเปน', 'ไซปรัส', 'ไตัหวัน',
       'ไทยเข้าร่วมโครงการ',
       'สาธารณรัฐสังคมนิยมเวียดนาม สาธารณรัฐสิงคโปร์ สหพัน',
       'สาธารัฐแอฟริกาใต้', 'เมียรม่า', 'เวียดนามและกัมพชา', '์ ไทย',
       'Thai', 'ุ', 'ณ สาธารณรัฐลัตเวีย และสาธารณรัฐลิทัวเนีย',
       'สาธารณรัฐลัตเวีย และ สาธารณรัฐลิทัวเนีย', 'จอร์เจีย',
       'สาธารณรัฐเมียนมา', 'สเปน และ อิตาลี', 'สาธารณรัฐจีน(ไต้หวัน)',
       'เวลส์', 'The Northern of Cyprus', 'มาเลเซีย และ สิงคโปร์',
       'อินโดนีเซีย และ เวียดนาม', 'สาธารณรัฐสังคมนิยมเวียดนาน',
       'สาธารณรัฐสโลวาเนีย', 'ออสเตรเลีย และ มาเลเซีย',

In [ ]:
'คาซัคสถาน และสาธารณรัฐตุรกี', 'จีน และฮ่องกง',
       'สาธารัฐประชาธิปไตยประชาชนลาว', 'ออสสเตรเลีย', 'ราชอาณาจักร',
       'อาณาจักรเนเธอร์แลนด์และสหรัฐสหรัฐสหรัฐอเมริกา', 'Belgium',
       'สาธารณรัฐรัสเซีย', 'เวียดนาม และลาว', 'บูรไน', 'ฺเบลเยียม',
       'เยอรมัน และ สวิตเซอร์แลนด์', 'สาธารณรัฐประชาธิปไตยประชาชนจีน',
       'จีน/ญี่ปุ่น/พม่า/ฟิลิปปินส์', 'สาธารณรัฐแห่งสหภาพเมียนมา',
       'สโลวีเนีย', 'สก๊อตแลนด์', 'ฟิจิ', 'อิหร่าน',
       'สาะารณรับเกาหลีใต้ใต้', 'ฝรังเศส', 'บัลแกเรีย', 'ไท', 'wmp',
       'สหพันธรัฐเยอรมนี', 'สหรัฐสหรัฐอเมริกา', 'สาธารณรัฐสโลวัก',
       'ไทย,มาเลเซีย', 'ไทยและมาเลเซีย', 'สาธารณรัฐมอริเชียส',
       'สาธารรัฐอินโดนีเซีย', 'กัมพูชา และลาว', 'สาธารณรัฐอินโดเนีย',
       'สหภาพเมียนมา', 'สาธารณรัฐแห่งสภาพพม่า', 'สาธารณรัฐเคนย่า',
       'ณ หลวงพระบาง ลาว', 'สาธารณรัฐอินโดนนีเซีย',
       'สาธาธรณรัฐประชาชนจีน', 'china', 'จีนและเยอรมันนี',
       'นิวซีแลนด์และออสเตรเลีย', 'สปป ลาว', 'รพ.ศิริราช   กรุงเทพฯ',
       'ิสิงคโปร์', 'เขตบริหารพิเศษฮ่องกง',

In [ ]:
df["ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ"] = df["ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ"].str.replace('','')
df["ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ"] = df["ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ"].str.replace('','')
df["ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ"] = df["ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ"].str.replace('','')
df["ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ"] = df["ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ"].str.replace('','')
'ราชอาณาจักรเบลเยียม เนเธอร์แลนด์ ลักเซมเบิร์ก', 'ไอร์แลนด์[# 5]',
       'สวิตเซอร์แลนด์  อิตาลี', 'รัฐอิสราเอล',
       'สาธารณรัฐประชาธิปไตยประชาชนแอลจีเรีย', 'สหราชอาณาจักร(อังกฤษ)',
       'สหราชอาณาจักรบ', 'ราชอาณาจักรเบลเยียม',
       'สมาพันธรัฐสวิสเซอร์ และ เยอรมนี', 'Taiwan', 'สาธารณรัฐบัลแกเรีย',
       'กรุงเทพ', 'ป่ารีส', 'รัฐสุลต่านโอมาน', 'ต่าง',
       'เครือรัฐออสเตรเลีย/นิวซีแลนด์', 'นอร์เวย์/สวีเดน',
       'ราชอาณาจักรสวาซิแลนด์', 'เยอรมัน เนเธอร์แลนด์ เบลเยียม',
       'ติมอร์-เลสเต-เลสเต', 'สาธารณรัฐพม่า', 'สาธารณรัฐฮังการี',
       'ไ้ต้หวัน', 'South Africa', 'สาธารณรัฐไอซ์แลนด์',
       'สาธารณรัฐฝรั่งเศส/สหราชอาณาจักร', 'สาธารณรัฐเฮลเลนิก',
       'ราชอาณาจักรนอร์เวย์และสวีเดน', 'สาธารณรัฐอาหรับอียิปต์ และตุรกี',
       'ฮ่องกงจีน', 'สาธาณรัฐตุรกี', 'รัฐกาตาร์',
       'สาธารณรัฐสิงคโปร์/มาเลเซีย',
       'สาธารณรัฐสังคมนิยมเวียดนาม และสาธารณรัฐประชาธิปไตย',
       'เขตปกครองพิเศษฮ่องกง', 'สหพันธ์สาธารณรัฐประชาธิปไตยเอธิโอเปีย',
       'อบรม', 'เยอรมนี /ฝรั่งเศส/สหพันธรัฐสวิส',
       'สาธารณรัฐประชาชนบังกลาเทศ', 'สาธารณรัฐสิงคโปร์/มาเลเวีย', 'Macau',
       'สาธารณรัฐอินโดนีเซีย/เวียดนาม', 'สถานที่  ณ  สิงคโปร์',
       'ลาว สาธารณรัฐสังคมนิยมเ', 'ลาว/พม่า', 'สหรััฐสหรัฐสหรัฐอเมริกา',
       'Czech  Republic', 'เยอรมันและเนเธอร์แลนด์',

In [ ]:
df['ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ'] = df['ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ'].astype(str) #เปลี่ยนค่าให้เป็นstr

In [ ]:


df["ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ"] = df["ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ"].str.replace('ประเทศ','')
df["ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ"] = df["ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ"].str.replace('+','')