<a href="https://colab.research.google.com/github/Suchada2000/test2/blob/main/Untitled14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [18]:
df = pd.read_excel('/content/drive/MyDrive/test/AB08-Study-Leave-Record_V00-ให้ นศ ช่วย cleansing.xlsx')

In [28]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,ดูข้อมูลจาก ประเภทการลาศึกษา ชีต LoVs,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,id,sequence,statuslist-อ้อม,ประเภทการลา,details,studylevel-ลิเดีย,Reason,sday,eday,place-เตย,location,country-แอน,country,scholarship,reference
1,100008,2,ฝึกอบรม ณ ต่างประเทศ,ไปฝึกอบรม ณ ต่างประเทศ,ภาษาญี่ปุ่น,NaN,NaN,1995-09-25,1996-07-09,Japan Foundation Japanese-Language Institute,Japan Foundation Japanese-Language Institute,แคนาดา,ญี่ปุ่น,The Japan Foundation Japanese Language Insititute,มข.3023/38 ลว.8ก.ย.38
2,100008,3,ลาศึกษาในประเทศ,ลาศึกษาในประเทศ,วิชาญี่ปุ่นศึกษา,ปริญญาโท,ปริญญาโท,1999-07-01,2001-06-30,มหาวิทยาลัยธรรมศาสตร์,มหาวิทยาลัยธรรมศาสตร์,ไทย,ไทย,ส่วนตัว,มข.1889/42 ลว.2 ก.ค.42
3,100008,4,ลาศึกษา ณ ต่างประเทศ,ลาศึกษา ณ ต่างประเทศ,ภาษาญี่ปุ่น,ปริญญาโท,NaN,2001-03-31,2002-03-30,Keio University,Keio University,ญี่ปุ่น,ญี่ปุ่น,Keio University Graduate Scholarship,มข.1479/44 ลว.20 มิ.ย.44
4,100009,5,ลาศึกษา ณ ต่างประเทศ,ลาศึกษา ณ ต่างประเทศ,Operative Dentistry,ปริญญาโท-เอก,NaN,1997-04-25,2002-10-24,Indiana University,Indiana University,สหรัฐอเมริกา,สหรัฐอเมริกา,รัฐบาล (ทบวงมหาวิทยาลัย),มข.1640/40 ลว.16 พ.ค.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230063,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN
230064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN

In [25]:
selected_column = df['ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ']

In [29]:
selected_column

0                   country-แอน
1                        แคนาดา
2                           ไทย
3                       ญี่ปุ่น
4                  สหรัฐอเมริกา
                  ...
230063                      NaN
230064                      NaN
230065                      NaN
230066                      NaN
230067
Name: ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ, Length: 230068, dtype: object

In [26]:
unique_values = selected_column.unique()

In [27]:
unique_values

array(['country-แอน', 'แคนาดา', 'ไทย', 'ญี่ปุ่น', 'สหรัฐอเมริกา',
       'ออสเตรเลีย', 'อังกฤษ', 'อิตาลี', 'นิวซีแลนด์', 'สิงคโปร์', 'จีน',
       'สหราชอาณาจักร', 'ลาว', 'เยอรมัน', 'ฟิลิปปินส์', 'มาเลเซีย',
       'ฮ่องกง', 'ยูโกสลาเวีย', 'เนเธอร์แลนด์', 'ปากีสถาน', 'เกาหลีใต้',
       'ไอร์แลนด์', 'เวียดนาม', 'อินเดีย', 'สวีเดน', 'เอธิโอเปีย',
       'ออสเตรีย', 'กรีซ', 'อิสราเอล', 'เบลเยียม', 'ไต้หวัน',
       'สวิตเซอร์แลนด์', 'ฝรั่งเศส', 'อินโดนีเซีย', 'สกอตแลนด์',
       'กัมพูชา', 'สาธารณรัฐเช็ก', 'นอร์เวย์', 'เชโกสโลวาเกีย', 'ฮังการี',
       'แทนซาเนีย', 'พม่า', 'รัสเซีย', 'โปแลนด์', 'เดนมาร์ก', 'บรูไน',
       'โครเอเชีย', 'สเปน', 'ศรีลังกา', 'โมนาโก', 'ราชอาณาจักรนอร์เวย์',
       'เนปาล', nan, 'ชิลี', 'เยอรมนี', 'แอฟริกาใต้', 'โปรตุเกส',
       'เม็กซิโก', 'ดูไบ', 'บราซิล', 'ตุรกี', 'มัลดีฟส์', 'มองโกเลีย',
       'สหรัฐอาหรับเอมิเรตส์', 'บังกลาเทศ', 'ฟินแลนด์', 'อาร์เจนตินา',
       'ราชอาณาจักรภูฏาน', 'ลักเซมเบิร์ก', 'อียิปต์', 'กาตาร์', 'กรีก',
       'สหรัฐอาหรับเอมิเรสส์', 'โรมาเนีย', 'เยอรมณี', 'สาธารณรัฐลัตเวีย',
       'ภูฏาน', 'เลบานอน', 'ฮ่องกงและสาธารณรัฐประชาชนจีน', 'เวียดนาม/ลาว',
       'ออสเตรเลีย/นิวซีแลนด์', 'สโลวาเนีย', 'จอร์แดน', 'กาน่า',
       'สาธารณรัฐฟิจิ', 'ซาอุดีอาระเบีย', 'สาธารณรัฐคิวบา',
       'สาธารณรัฐไซปรัส', 'บอตสวานา', 'เคนยา', 'บูร์กินาฟาโซ',
       'สาธารณรัฐมอลตา', 'เช็ก', 'ฝรั่งเศสและออสเตรีย', 'ลาวและเวียดนาม',
       'พิลิปปินส์', 'ใน', 'สวิสเซอร์แลนด์ และฝรั่งเศส', 'อูกันดา',
       'ตูนีเซีย', 'ลาว เวียดนาม จีน', 'สาธารณรัฐประชาชนจีน',
       'มาดากัสการ์โมซัมบิกและแอฟริกาใต้', 'ราชอาณาจักรเนเธอร์แลนด์',
       'สาธารณรัฐนามิเบีย', 'สาธารณรัฐประชาธิปไตยประชาชนลาว/เวียดนาม',
       'ลาว/เวียดนาม/ สาธารณรัฐประชาชนจีน', 'จีน/เวียดนาม/ลาว', 'ยูเครน',
       'ห้องประชุมนพดล ทองโสภิต', 'อังกฤษ/ฝรั่งเศส',
       'เยอรมันนี เนเธอร์แลนด์ เบลเยี่ยม ลักเซมเบอร์ก',
       'นอร์เวย์และสวีเดน', 'สเปน ฝรั่งเศส อิตาลี สวิสเซอร์แลนด์',
       'ไมโครนีเชีย', 'เฮติ', 'สโลวาเนียและเยอรมัน', 'ใต้หวัน',
       'ห้องประชุมจำลอง   มุ่งการดี ชั้น 4  อาคารสมเด็จพระ',
       'มาเลเซีย/สิงค์โปร์', 'เกาหลีและจีน', 'ฮ่องกงและเกาหลีใต้',
       'สาธารณรัฐเกาหลี', 'สิบสองปันนาสาธารณรัฐประชาชนจีน', 'สิงค์โปร์',
       'มาเลเซียและสิงคโปร์', 'สวิสเซอร์แลนด์ และ อิตาลี',
       'อังกฤษ/สวิสเซอร์แลนด์/เดนมาร์ก/ไอแลนด์', 'มอลตา', 'เวียตนาม',
       'อิตาลี / ฝรั่งเศส', 'ลาว / จีน', 'Mongoltia', 'สาธารณรัฐมัลดีฟล์',
       'ลาว/เวียดนาม/กัมพูชา', 'นิวซีแลนด์/ออสเตรเลีย', 'เวียดนามและจีน',
       'ภูฏาณ', 'เกาหลีและฮ่องกง', 'สหภาพพม่า  สาธารณรัฐประชาชนจีน',
       'ลิทัวเนีย', 'สวิสเซอร์แลนด์โปรตุเกส', 'สหราชอาณาจักร,เนเธอแลนด์',
       'ราชอาณาจักรสเปน', 'ศธ 0514.7.3.13/ว2636/54',
       'ออสเตรเลียและสาธารณรัฐเช็ก', 'สาธารณรัฐเซเชลส์',
       'สาธารณรัฐไอร์แลนด์', 'โมร็อกโก', 'เยอรมัน,ฝรั่งเศส,อังกฤษ',
       'เกาลีใต้', 'เช็ค', 'สหรัฐเม็กซิโก', 'สาธารณรัฐสิงค์โปร์',
       'สาธารณรัฐฝรั่งเศส', 'ิอิตาลี', 'สาธารณรัฐตุรกี',
       'ราชอาณาจักรนอรเวย์', 'อินโดนีเซีย/จีน', 'Switzerland และ  Italy',
       'ห้องประุมสมาคมศิษย์เก่า เวลา 12.00-13.00 น.', 'South Korea',
       'สาธารณรัฐแห่งสหภาพเมียนมาร์', 'สาธารณัฐเกาหลีใต้',
       'สาธารณรัฐจิบูตีและฝรั่งเศส', 'สาธารณรัฐอิสลามอิหร่าน',
       'อินโดนีเซียและสิงคโปร์',
       'ราชอาณาจักรสวีเดนNational Veterinary Institute (SV',
       'กรมอนามัย  กระทรวงสาธารณสุข  เวลา 10.00-16.00 น.', ' ฝรั่งเศส',
       'สหพันธ์สาธารณรัฐเยอรมนี สาธารณรัฐฝรั่งเศส และสมาพั',
       'ฝรั่งเศส อิตาลี สวิตเซอร์แลนด์',
       'สาธารณรัฐฝรั่งเศส สาธารณรัฐอิตาลี สมาพันธรัฐสวิส',
       'สาธารณรัฐประชาธิปไตยประชาชนลาว', 'DATA NOT FOUND', 'เกาหลีเหนือ',
       'จีน-ไต้หวัน', 'เอกวาดอร์', 'สาธารณรัฐสโลวักและเดนมาร์ก',
       'เบลเยี่ยมและเนเธอร์แลนด์', 'สโลวาเกีย',
       'สาธารณรัฐเกาหลี (เกาหลีใต้)', 'โปรตุเกต', 'ไอซ์แลนด์',
       'สาธารณรัฐแห่งสหภาพพม่า', 'สาธารณรัฐลิทัวเนีย', 'ราชอาณาจักรเนปาล',
       'ิอินเดีย', 'สาธารณรัฐไอซ์แลนด์/สหราชอาณาจักร', 'สาธารณรัฐเช็ค',
       'สาธารณรัฐแอฟริกาใต้', 'ราชอาณาจักรเดนมาร์ก', 'สาธารณรัฐฟินแลนด์',
       'ณ เมืองบาหลี อินโดนีเซีย',
       'สาธารณรัฐประชาธิปไตยประชาชนลาว และสาธารณรัฐสังคมนิ', 'บลาซิล',
       'สาธารณรัฐเซอร์เบีย', 'ลาว เวียดนาม จีนและกัมพูชา',
       'สหราชอาณาจ้กร', 'สหพันธ์สาธารณรัฐเยอรมนีและออสเตรเลีย',
       'สาธาณรัฐรัสเซีย', 'ฝรั่งเศษ', 'สิงคโปร์และมาเลเซีย',
       'สาธารณรัฐสโลวีเนีย', 'สาธารณรัฐมาซิโดเนีย', 'สาธารณรัฐเคนยา',
       'รัฐอิสราเอล จอร์แดน คูเวต', 'ู', 'กัมพูชาและเวียดนาม',
       'สาธารณรัฐประชาธิปไตยประชาชนเกาหลี', 'สาธารณรัฐโปแลนด์',
       'ราชอาณาจักรโมร็อกโก', 'ลาวและกัมพูชา',
       'ราชอาณาจักรเบลเยียม เนเธอร์แลนด์ ลักเซมเบิร์ก', 'ไอร์แลนด์[# 5]',
       'สวิตเซอร์แลนด์  อิตาลี', 'รัฐอิสราเอล',
       'สาธารณรัฐประชาธิปไตยประชาชนแอลจีเรีย', 'สหราชอาณาจักร(อังกฤษ)',
       'สหราชอาณาจักรบ', 'ราชอาณาจักรเบลเยียม',
       'สมาพันธรัฐสวิสเซอร์ และ สหพันธ์สาธารณรัฐเยอรมนี',
       'สาธารณรัฐบัลแกเรีย', 'ปารีส', 'รัฐสุลต่านโอมาน', 'ต่าง',
       'นอร์เวย์/สวีเดน', 'ราชอาณาจักรสวาซิแลนด์',
       'เยอรมัน เนเธอร์แลนด์ เบลเยี่ยม',
       'สาธารณรัฐประชาธิปไตยติมอร์-เลสเต', 'สาธารณรัฐสหภาพพม่า',
       'สาธารณรัฐฮังการี', 'ไ้ต้หวัน', 'สาธารณรัฐไอซ์แลนด์',
       'ฝรั่งเศส/สหราชอาณาจักร', 'สาธารณรัฐเฮลเลนิก',
       'ราชอาณาจักรนอร์เวย์และราชอาณาจักรสวีเดน',
       'สาธารณรัฐอาหรับอียิปต์และตุรกี', 'ฮ่องกงสาธารณรัฐประชาชนจีน',
       'สาธาณรัฐตุรกี', 'รัฐกาตาร์', 'สิงคโปร์/มาเลเซีย',
       'สหพันธ์สาธารณรัฐประชาธิปไตยเอธิโอเปีย', 'อบรม',
       'เยอรมนี /ฝรั่งเศส/สหพันธรัฐสวิส', 'สาธารณรัฐประชาชนบังกลาเทศ',
       'มาเก๊า', 'อินโดนีเซีย/เวียดนาม', 'สถานที่  ณ  สิงคโปร์',
       'สาธารณรัฐประชาธิปไตยประชาชนลาว สาธารณรัฐสังคมนิยมเ',
       'สาธารณรัฐประชาธิปไตยประชาชนลาว/พม่า', 'สหรััฐอเมริกา',
       'เยอรมันและเนเธอร์แลนด์', 'สาธารณรัฐคาซัคสถาน และสาธารณรัฐตุรกี',
       'สาธารณรัฐประชาชนจีน และฮ่องกง', 'ราชอาณาจักร',
       'อาณาจักรเนเธอร์แลนด์และสหรัฐอเมริกา', 'สาธารณรัฐรัสเซีย',
       'เวียดนามและลาว', 'บูรไน', 'ฺเบลเยี่ยม',
       'เยอรมัน และ สวิสเซอร์แลนด์', 'จีน/ญี่ปุ่น/พม่า/ฟิลิปปินส์',
       'สโลวีเนีย', 'สก๊อตแลนด์', 'ฟิจิ', 'อิหร่าน', 'สาะารณรับเกาหลี',
       'ฝรังเศส', 'บัลแกเรีย', 'wmp', 'ประชุม', 'สาธารณรัฐสโลวัก',
       'ไทย,มาเลเซีย', 'ไทยและมาเลเซีย', 'สาธารณรัฐมอริเชียส', ' Turkey',
       '0', 'สหภาพเมียนมาร์', 'กัมพูชา และสาธารณรัฐประชาธิปไตยประชาชนลาว',
       'อินโดเนีย', 'สาธารณรัฐเคนย่า',
       'ณ หลวงพระบาง สาธารณรัฐประชาธิปไตยประชาชนลาว', 'จีนและเยอรมนี',
       'นิวซีแลนด์และออสเตรเลีย', 'ิสิงคโปร์', 'สมาพันธรัฐสวิส',
       'สมาชิกเชงเกน (อิตาลี สวิสเซอร์แลนด์ ฝรั่งเศส และเน',
       'สมาพันธรัฐรัสเซีย', 'เกาหลี', 'สาธารณรัฐโครเอเซีย',
       'ราชอาราจักสเปน', 'ไซปรัส', 'ไตัหวัน', 'เวียดนาม สิงคโปร์',
       'เวียดนามและกัมพูชา', '์ ไทย', 'ุ',
       'สาธารณรัฐลัตเวียและสาธารณรัฐลิทัวเนีย', 'จอร์เจีย',
       'สเปนและอิตาลี', 'เวลส์', 'ไซปรัสเหนือ', 'อินโดนีเซียและเวียดนาม',
       'สาธารณรัฐสโลวาเนีย', 'ออสเตรเลียและมาเลเซีย',
       'สหราชอาณาจักรบริเตนใหญ่และไอร์แลนด์เหนือ',
       'ณ ห้องบรรยาย 201 ชั้น 2 อาคารศูนย์แพทยศาสตร์ศึกษาช',
       'เขตบริหารพิเศษมาเก๊าแห่งสาธารณรัฐประชาชนจีน',
       'ราชอาณาจักรเบลเยี่ยม', 'ญี่ปุ่น', 'เบลเยียมและเนเธอร์แลนด์',
       'เบลเยียม อังกฤษ เนเธอแลนด์', 'ญี่ปุ่นและสหรัฐอเมริกา',
       'สิงคโปร์ มาเลเซียและฟิลิปปินส์', 'สิงคโปร์ ฟิลิปปินส์และมาเลเซีย',
       'ปาปัวนิวกินี', 'สหราชอาณาจักรและฝรั่งเศส',
       'สิงคโปร์ เมียนมาร์ มาเลเซีย กัมพูชา', 'จีน เกาหลีใต้',
       'เวียดนาม.', 'สาธารณรัฐโปรตุเกส', 'เนเธอแลนด์',
       'เบลเยียม เยอรมันนี', 'เบลเยียม นอร์เวย์',
       'เเบลเยี่ยม เยอรมันนี นอร์เวย์', 'สมพันธรัฐสวิส',
       'สหพันธ์สาธารณรับเยอรมนี', 'รัฐเซีย', 'จึน', 'ไต้หวันและจีน',
       'เปรู', 'โปรแลนด์', 'สหรัฐอเมริกา และ แคนาดา', 'เบลเยียม,เยอรมนี',
       'เซอร์เบีย', 'มอลตา,บัลแกเรีย', 'มาเลเซีย,สิงคโปร์',
       'เยอรมนีและออสเตรีย', 'ลัทเวีย', 'บรัสเซลล์ และ เบลเยี่ยม',
       'ลัตเวีย', 'คอสตาริกา', 'ัไทย', 'คาซัคสถาน', 'สาธารณรัฐเฮเลนิก',
       'สาธารณรัฐฝรั่งเศส และ สหพันธ์สาธารณรัฐเยอรมัน',
       'เช็กเกียและเยอรมนี', 'ไท่ย', 'เยอรมนีและเนเธอร์แลนด์',
       'เนเธอร์แลนด์และฝรั่งเศส', 'นอร์เวย์ และ สวิสเซอร์แลนด์',
       'สาธารณรัฐชิลี', 'แม็กซิโก', 'เนเธอร์แลนด์ และ เบลเยี่ยม',
       'เนเธอร์แลนด์ และเบลเยี่ยม', 'ยูกันดา', 'สก็อตแลนด์',
       'ทรานส์นิสเตรีย', 'สาธารณรัฐโครเอเชีย', 'อาเจนติน่า', 'กานา',
       'สาธารณรัฐเช็กและเนเธอร์แลนด์', 'อาเซอร์ไบจาน',
       'สิงคโปร์และอินโดนีเซีย', 'กรีซและเนเธอร์แลนด์',
       'เยอรมนี ออสเตรียและสวิตเซอร์แลนด์', 'อุซเบกิสถาน',
       'สวีเดน และ เอสโตรเนีย', 'ญี่ปุ่น และ เกาหลีใต้',
       'สาธารณรัฐแห่งสหภาพเมียนมา', 'กัมพูชาและฟิลิปปินส์',
       'เดนมาร์กและสหราชอาณาจักร', 'อินโดนีเซียและติมอร์เลสเต',
       'สาธารณรัฐสหภาพเมียนมาร์', 'ราชอาณาจักรฮัชไมต์จอร์แดน',
       'เยอรมนีและฝรั่งเศส', 'เกาหลีใต้,ไต้หวัน',
       'สาธารณัฐเกาหลี (เกาหลีใต้)', 'เกาหลีใต้ และ ไต้หวัน',
       ' Czeech Republic', 'สิงค์โปร', 'เมือง Athens  Greece',
       'เมืองโฮจีมินทร์ เวียดนาม', '-', 'งบนอกเหนืองบประชุมวิชาการ',
       '้ไทย', 'ออสเตรีย(ไทย)', 'Mumbai India', 'ไทย์', '์ไทย', 'online',
       'สราชอาณาจักร', 'ไทย/สหรัฐอเมริกา', 'สวิตเซอร์แลนด์,นอร์เวย์',
       'ไ่ทย', 'ิไทย', 'สาธารณรัฐเปรู', 'ฝรั่งเศสและสเปน',
       'สหราชอาณาจักรบริเตนใหญ่และไอร์แลนด์', 'ราชอาณาจักรสกอตแลด์',
       'ฟินแลนด์ และ สาธารณรัฐเอสโตเนีย', 'ปารากวัย',
       'ฝรั่งเศส และ สหราชอาณาจักร', 'สาธารณรัฐเฮลเลนิก (กรีซ)',
       'สมาพันธรัฐสวิสและสหพันธ์สาธารณรัฐเยอรมนี', 'Thailand',
       'ออสเตรเลีย และนิวซีแลนด์', 'เอสโตเนีย', 'สำนักงานอธิการบดี',
       'จังหวัดระยอง', 'ราชอาณาจักรเบลเยี่ยม และ สหพันธ์สาธารณรัฐเยอรมนี',
       'สหราชอาณาจักรและเยอรมนี', 'ญี่ปุน',
       'บอสเนียและเฮอร์เซโกวีนา และ ฮังการี', 'มาเลเซีย และ สิงค์โปร์',
       'สาธารณรัฐสังคมนิยมประชาธิปไตยศรีลังกา กรุงเทพมหานค',
       'เนการาบรูไนดารุสซาลาม', 'จีนและลาว', 'เกาหลีใต้และญี่ปุ่น',
       'สวีเดน เอสโตเนียและฟิลิปปินส์',
       'สาธารณรัฐประชาธิปไตยติมอร์ - เลสเต',
       'ราชอาณาจักรสวีเดน เอสโตเนีย และฟินแลนด์', 'end',
       '                     '], dtype=object)

In [20]:
correction_dict = {'ประเทศสิงค์โปร์บริษัท เฮ็ลธ อินโนเวณัน จำกัด': 'สิงคโปร์','เกาหลีใต้ใต้ใต้ และ ไต้หวัน': 'เกาหลีใต้และไต้หวัน', ' Czeech Republic': 'กรีซ',
       'Dubrovnik สาธารณรัฐโครอเชีย': 'โครเอเชีย', 'สิงค์โปร': 'สิงคโปร์','เมือง Athens  Greece': 'กรีซ',
       'ออสเตเรีย': 'ออสเตรีย','เมืองโฮจีมินทร์ เวียดนาม': 'เวียดนาม',
       'งบนอกเหนืองบวิชาการ': 'ไทย', 'ราชอาณาจักรสกอตแลนด์':'สกอตแลนด์', 'Malaysia': 'มาเลเซีย','สหพันธ์สาธารณรัฐประชาธิปไตยเนปาล':'เนปาล','ลาว และสาธารณรัฐสังคมนิ':'ลาวและเวียดนาม',
                   'ณ เมืองบาหลี อินโดนีเซีย':'อินโดนีเซีย','Greece':'กรีซ','สหพันธ์สาธารณรัฐบราซิล':'บลาซิล',
'เมือง Vancouver  แคนาดา':'แคนาดา','ลาว เวียดนาม จีนตอนใต้ และกัมพูชา':'ลาว เวียดนาม จีนและกัมพูชา','สาธาณรัฐประชาชนลาว':'ลาว','ดูไบร์':'ดูไบ','Indonesia':'อินโดนีเซีย',
'สหภาพเมีนม่าร์':'พม่า','ราชอาณาจักรไย':'ไทย','เยอรมณี':'เยอรมนี','ราชอาณาจักรไทย':'ไทย','ราชอาณาจักรกัมพูชาและสาธารณรัฐสังคมนิยมเวียดนาม':'กัมพูชาและเวียดนาม','สาธารณรัฐประชาธิปไตยประชาชนเกาหลีใต้ใต้':'เกาหลีใต้',
'สาธารณรัฐสังคมนิยมประชาธิปไตยศรีลังกา':'ศรีลังกา','ราชอาณาจักรไทร':'ไทย','สหราชอาณาจักรอังกฤษ':'สหราชอาณาจักร','สาธารณรัฐฝรั่งเศส สาธา รณรัฐอิตาลี สมาพันธรัฐสวิส':'ฝรั่งเศส อิตาลี สวิตเซอร์แลนด์',
'สาธาณรัฐประชาธิปไตยประชาชนลาว':'ลาว','สาธารณรัฐประชาชนธิปไตยประชาชนลาว':'ลาว','สาธารณรับประชาธิปไตยประชาชนลาว':'ลาว','เกาหลีใต้ใต้เหนือ':'เกาหลีใต้',
'นิวส์ซีแลนด์':'นิวซีแลนด์','บรูไนดารุสซาลาม':'บรูไน','สาธารณรัฐสโลวัก และเดนมาร์ก':'สาธารณรัฐสโลวักและเดนมาร์ก','เกาหลีใต้ใต้ใต้ (เกาหลีใต้ใต้ใต้)':'เกาหลีใต้ใต้','สาธารณรัฐเวียดนาม':'เวียดนาม','สาธารณรัญอินเดีย':'อินเดีย',
'vietnam':'เวียดนาม','สาธารณรัฐอินเดีย':'อินเดีย','สาธารรัณสังคมนิยมเวียดนาม':'เวียดนาม','สาธารรัณสังคมนิยมเวียดนาม':'เวียดนาม','South เกาหลีใต้ใต้ใต้':'เกาหลีใต้',
'สาธารณรัฐแห่งพม่า':'พม่า','กรมอนามัย  กระทรวงสาธารณสุข  เวลา 1.-16. น.':'ไทย','สาธารณัฐเกาหลีใต้ใต้ใต้':'เกาหลีใต้','สาธารณรัฐฟิลิปปินส์':'ฟิลิปปินส์',
'สาธารณรัฐมาเลเซีย':'มาเลเซีย','เมือง sapporo':'ญี่ปุ่น','สาธารณรัฐจิบูตี และสาธารณรัฐฝรั่งเศส':'สาธารณรัฐจิบูตีและฝรั่งเศส','สวีเดนNational Veterinary Institute (SV':'สวีเดน',
'หอศิลป์สมเด็จพระนางเจ้าสิริกิติ์ พระบรมราชินีนาถ ถ':'ไทย','USA':'สหรัฐอเมริกา','สาธารณรัฐอินโดนีเซียและสาธารณรัฐสิงคโปร์':'อินโดนีเซียและสิงคโปร์','สิงค์โปร์':'สิงคโปร์','ราชอาณาจักรสวีเดน':'สวีเดน','สาธารณรัฐคาซัคสถาน':'คาซัคสถาน','สาธารณรัฐประชาธิปไตยติมอร์':'ติมอร์-เลสเต',
'สาธารณรัฐเกาหลี':'เกาหลีใต้','สาธารณรัฐเกาหลีใต้':'เกาหลีใต้','สาธารณรัฐประชาธิปไตยชาชนลาว':'ลาว','ราชอาณาจักรสวีเดน สาธารณรัฐเอสโตเนียและสาธารณรัฐฟิ':'สวีเดน เอสโตเนียและฟิลิปปินส์',
'สาธารณรัฐประชาชนจีน และ สาธารณรัฐประชาธิปไตยประชาช':'จีนและลาว','สาธารณรัฐเกาหลี (เกาหลีใต้) และ ญี่ปุ่น':'เกาหลีใต้และญี่ปุ่น','สาธารณรัฐเกาหลีใต้และญี่ปุ่น':'เกาหลีใต้และญี่ปุ่น',
'ไทย+':'ไทย', '็ไทย':'ไทย','Lao':'ลาว','เยอรมมนี':'เยอรมนี','สาธารณรัฐประชาธิปไตยประชาชาลาว':'ลาว','สาธารณรัฐสังคมนิมเวียดนาม':'เวียดนาม','ไต้หวันศธ0514.26....1.1/467  ลว. 15 .ก.พ.55':'ไต้หวัน',
 'Italy':'อิตาลี','Korea':'เกาหลีใต้','ห้องประุมสมาคมศิษย์เก่า เวลา 12.00-13.00 น':'ไทย','ราชอาณาจักรกัมพูชาทุน':'กัมพูชา', 'มาเลเซีย  และสิงคโปร์':'มาเลเซียและสิงคโปร์',
 'Turkey':'ตุรกี','Brunei':'บรูไน','สาธารณรัฐส้งคโปร์':'สิงคโปร์','ห้องนพดล ทองโสภิต':'ไทย','สาธารณรัญอินเดีย':'อินเดีย','Germany':'เยอรมนี','อังกฤษ/ฝรั่งเศล':'อังกฤษ/ฝรั่งเศส','Singapore':'สิงคโปร์',
'Spain':'สเปน','Micronesia':'ไมโครนีเชีย','Haiti':'เฮติ','ใต้หวัน':'ไต้หวัน','ห้องจำลอง   มุ่งการดี ชั้น 4  อาคารสมเด็จพระ':'ไทย',
'ไืทย':'ไทย','อิตา':'อิตาลี','ฝรั่งเศษ':'ฝรั่งเศส','เกาหลีใต้ใต้และจีน':'เกาหลีใต้และจีน','ฮ่องกงและเกาหลีใต้ใต้ใต้':'ฮ่องกงและเกาหลีใต้',
'สิบสองปันนาจีน':'จีน','สาธารณรัฐไต้หวัน':'ไต้หวัน','ตุรกรี':'ตุรกี','ไ':'ไทย','สปน':'สเปน','CHINA':'จีน',
'ไิทย':'ไทย','Malta':'มอลตา','สิงคโปร์บริษัท เฮ็ลธ อินโนเวณัน จำกัด':'สิงคโปร์','เวียนามและจีน':'เวียดนามและจีน','เกาหลีใต้ใต้และฮ่องกง':'เกาหลีใต้และฮ่องกง',
'พม่า  จีน':'พม่า จีน','Lithuania':'ลิทัวเนีย','ลิธัวเนีย':'ลิทัวเนีย','ราชอาณาจักรกัมพูชา':'กัมพูชา','สาธารณัฐประชาธิปไตยประชาชนลาว':'ลาว','สวิตเซอร์แลนด์ และ อิตาลี':'สวิตเซอร์แลนด์และอิตาลี',
                    'สหพันธรัฐรัสเซีย':'รัสเซีย', 'ไืทยในส่วนราชการ':'ไทย','ออสเตรเลียและเชค':'ออสเตรเลียและสาธารณรัฐเช็ก','seychelles':'สาธารณรัฐเซเชลส์',
 'โมร็อกโค':'โมร็อกโก', 'เยอรมนี,ฝรั่งเศส,อังกฤษ':'เยอรมนี,ฝรั่งเศส,สหราชอาณาจักร','ไต้หวัน1':'ไต้หวัน', 'ไำทย':'ไทย',
 'ไทย.':'ไทย','Switzerland และ  อิตาลี':'สวิตเซอร์แลนด์และอิตาลี','สาะรณรัฐประชาธิปไตยประชาชนลาว':'ลาว', 'เขตบริหารพิเศษฮ่องกงแห่งสาธารณรัฐประชาชนจีน':'ฮ่องกง',
  'ฮ่องกง สาธารณับประชาชนขจีน':'ฮ่องกง','เกาหลี':'เกาหลีใต้', 'สาธารณรัฐประชาธิปไตยประชาชนลาว':'ลาว','เบลเยี่ยม':'เบลเยียม',
   'สวิสเซอร์แลนด์':'สวิตเซอร์แลนด์', 'สาธารณรัฐเชค':'สาธารณรัฐเช็ก','เชคโกสโลวาเกีย':'เชโกสโลวาเกีย','สาธารณรัฐประชาชนจีน':'จีน',
    'เมียนมาร์':'พม่า', 'สาธารณรัฐออสเตรีย':'ออสเตรีย', 'โปร์แลนด์':'โปแลนด์','เดนมาร์ค':'เดนมาร์ก', 'โครเอเซีย':'โครเอเชีย','สหราชอาณาจักรบริเตนใหญ่และไอร์แลนด์เหนือ':'สหราชอาณาจักร',
    'โมนาโค':'โมนาโก', 'สาธารณรัฐอิตาลี':'อิตาลี', 'เยอรมนีนี':'เยอรมนี', 'สหพันธ์สาธารณรัฐเยอรมนี':'เยอรมนี','czech republic':'สาธารณรัฐเช็ก','อัฟริกาใต้':'แอฟริกาใต้', 'สหภาพพม่า':'พม่า',
    'สาธารณรัฐอิสลามปากีสถาน':'ปากีสถาน','United Arab Emirates':'สหรัฐอาหรับเอมิเรตส์','อ่องกง':'ฮ่องกง','สาธารณรัญอินเดีย':'อินเดีย','สมาพันธรัฐสวิส':'สวิตเซอร์แลนด์','เครือรัฐออสเตรเลีย':'ออสเตรเลีย',
'สาธารณรัฐอินโดนีเซีย':'อินโดนีเซีย','Saudi Arabia':'ซาอุดีอาระเบีย','Austria':'ออสเตรีย','สาธารณรัฐสิงคโปร์':'สิงคโปร์',
'Burkina Faso':'บูร์กินาฟาโซ','สหพันธรัฐสวิส':'สวิตเซอร์แลนด์','สาธารณรัฐสังคมนิยมเวียดนาม':'เวียดนาม','สาธารณรัฐจีน':'จีน',
'ลาว ลาว และ เวียดนาม':'ลาวและเวียดนาม','สปป.ลาว':'ลาว','ใน':'ไทย','จีน (ใต้หวัน)':'ไต้หวัน','สวิตเซอร์แลนด์ และฝรั่งเศส':'สวิตเซอร์แลนด์และฝรั่งเศส',
'กรุงเทพฯ':'ไทย','Australia':'ออสเตรเลีย','England':'สหราชอาณาจักร','มาดากัสการ์โมซัมบิก และแอฟริกาใต้':'มาดากัสการ์โมซัมบิกและแอฟริกาใต้',
'ราชอาณาจักรเนเธอแลนด์':'ราชอาณาจักรเนเธอร์แลนด์','Japan':'ญี่ปุ่น','ราชอานาจักรกัมพูชา':'กัมพูชา','Hong Kong':'ฮ่องกง','เยอรมันนี':'เยอรมนี',
'Czech Republic':'สาธารณรัฐเช็ก','มัลดีฟล์':'มัลดีฟส์','บังคลาเทศ':'บังกลาเทศ','ควีนส์แลนด์':'ออสเตรเลีย','สาธารณรัฐอาหรับอียิปต์':'อียิปต์',
'สาธารณรัฐโปรตุเกส':'โปรตุเกส','สาธารณรัฐอาหรับเอมิเรสต์':'สหรัฐอาหรับเอมิเรสส์','Beigium':'เบลเยียม','สหพันธ์สาธารณรัฐเยอมณี':'เยอรมณี',
'นอกคณะ':'ไทย','ในคณะ':'ไทย','เกาหลีใต้ใต้ใต้ใต้':'เกาหลีใต้','สหรัฐสหรัฐสหรัฐอเมริกา':'สหรัฐอเมริกา','เกาหลีใต้ใต้ใต้':'เกาหลีใต้ใต้',
'เกาหลีใต้ใต้':'เกาหลีใต้','อเมริกกา':'สหรัฐอเมริกา','มหาวิทยาลัยมหิดล':'ไทย','ไทย / สหรัฐอเมริกา':'ไทย/สหรัฐอเมริกา','ไทยข':'ไทย',
'สหราชอาณาจักรบริเตนใหญ่ และไอร์แลนด์เหนือ':'สหราชอาณาจักรบริเตนใหญ่และไอร์แลนด์','สหราชอาณาจักรสกอตแลด์':'ราชอาณาจักรสกอตแลด์',
'โรงสีข้าวพระราชทาน น่าน':'ไทย','ห้องประชุมสำนักงาน คณะเทคนิคการแพทย์':'ไทย','คณะเทคนิคการแพทย์':'ไทย','สหราชอาณาจักร และ เยอรมนี':'สหราชอาณาจักรและเยอรมนี',
'เกาหลีใต้ใต้ (เกาหลีใต้ใต้) และ ญี่ปุ่น':'เกาหลีใต้และญี่ปุ่น','Sunstun makeup-studio':'ไทย','สวีเดน เอสโตเนีย และฟินแลนด์':'สวีเดน เอสโตเนียและฟินแลนด์',
'เยอรมนี และเนเธอร์แลนด์':'เยอรมนีและเนเธอร์แลนด์','ณ  คณะสาธารณสุขศาสตร์  มหาวิทยาลัยขอนแก่น':'ไทย','ห้องประชุม Crystal Ballroom โรงแรมตวันนา กรุงเทพ':'ไทย',
'ทรานส์นิสเตรี':'ทรานส์นีสเตรีย','ไืน':'ไทย','ไท0':'ไทย','กทม':'ไทย','เยอรมันนี และ ฝรั่งเศส':'เยอรมนีและฝรั่งเศส','ห้องประชุม ๘๐๙ ราชวิทยาลัยสูติฯ ชั้น ๘ อาคารเฉลิมพ':'ไทย',
'ณ โรงแรม The Athenee Hotel กรุงเทพฯ':'ไทย','สวีเดน และ เอสโตรเนี':'สวีเดนและเอสโตเนีย','สาธารณประชาชนจีน':'จีน','อเมริกา':'สหรัฐอเมริกา','โรงแรมเจริญธานีปริ๊นเซ็ส  จังหวัดขอนแก่น':'ไทย','ขอนแก่น  ไทย':'ไทย','รพ. ศรีนครินทร์  ม. ขอนแก่น':'ไทย','ไทย, มาเลเซีย':'ไทย,มาเลเซีย',
'ไทย และ มาเลเซีย':'ไทยและมาเลเซีย','สาธารณัฐอิตาลี':'อิตาลี','ราชกาณาจักรกัมพูชา':'กัมพูชา','เยรอมนี':'เยอรมนี','Mauritius':'สาธารณรัฐมอริเชียส',
' ตุรกี':'ตุรกี','ณ ห้องบรรยาย 21 ชั้น 2 อาคารศูนย์แพทยศาสตร์ศึกษาช':'ไทย','สาธารณรัฐฟินแลน์':'สาธารณรัฐฟินแลนด์',
'สหราช-อาณาจักร (United Kingdom)':'สหราชอาณาจักร','ขอนแก่น':'ไทย','เขตบริหารพิเศษมาเก๊าแห่งจีน':'มาเก๊า','TAIWAN':'ไต้หวัน',
'สาธารณรัฐเยอรมณี':'เยอรมณี','สาธารรัฐประชาชนจีน':'จีน','ญี่ปุ่่น':'ญี่ปุ่น','/ไทย':'ไทย','สหภาพเมียมาร์':'พม่า','Myanmar':'พม่า', 'เมียนมา':'พม่า', 'บรัสเซลล์ และ เบลเยียม':'บรัสเซลล์และเบลเยียม','สหรราชอาณาจักร':'สหราชอาณาจักร',
 'ไอซ์แลนด์เหนือ':'ไอซ์แลนด์','คอสตาริก้า':'คอสตาริกา','Kazakhstan':'คาซัคสถาน',
 'สาธารณรัฐประชาธิปไจยประชาชนลาว':'ลาว','Czech Republic และสาธารณรัฐเยอรมนี':'เช็กเกียและเยอรมนี','เนเธอร์แลนด์ และ ฝรั่งเศส':'เนเธอร์แลนด์และฝรั่งเศส',
 'ณ   โรงแรมรามาการ์เดนส์   กรุงเทพฯ':'ไทย','โรงแรมรามาการ์เดนส์   กรุงเทพฯ':'ไทย','สาธารณรัฐสหภาพเมียนมา':'พม่า','สาธารณรัฐเช็ก และ เนเธอร์แลนด์':'สาธารณรัฐเช็กและเนเธอร์แลนด์',
 'สิงคโปร์ และ อินโดนีเซีย':'สิงคโปร์และอินโดนีเซีย','สาธารณรัฐจีน (ไต้หวัน)':'ไต้หวัน', 'เยอรมนี ออสเตรีย และสวิตเซอร์แลนด์':'เยอรมนี ออสเตรียและสวิตเซอร์แลนด์',
                   'สวีเดนและเอสโตเนียย':'สวีเดนและเอสโตเนีย',  'ญี่ปุ่น และ เกาหลีใต้ใต้ใต้':'ญี่ปุ่นและเกาหลีใต้'
     ,'กัมพูชา และ ฟิลิปปินส์':'กัมพูชาและฟิลิปปินส์','เดนมาร์ก และ สหราชอาณาจักร':'เดนมาร์กและสหราชอาณาจักร','อินโดนีเซีย และติมอร์เลสเต':'อินโดนีเซียและติมอร์เลสเต',
     'ไทน':'ไทย','เยอรมนี และ ฝรั่งเศส':'เยอรมนีและฝรั่งเศส','เกาหลีใต้ใต้ใต้,ไต้หวัน':'เกาหลีใต้,ไต้หวัน','สาธารณัฐเกาหลีใต้ใต้ (เกาหลีใต้ใต้ใต้)':'เกาหลีใต้'
    ,'สาธารณรัฐเยอรมันนี':'เยอรมนี','สหราชอาณาจักร-บริเตนใหญ่และไอร์แลนด์เหนือ':'สหราชอาณาจักรบริเตนใหญ่และไอร์แลนด์เหนือ',
'สมาพันธรัฐสวิซ':'สมาพันธรัฐสวิส','ลาว และ เวียดนาม':'ลาวและเวียดนาม','เบลเยียม และเนเธอร์แลนด์':'เบลเยียมและเนเธอร์แลนด์',
'ญี่ปุ่นและสหรัฐสหรัฐสหรัฐอเมริกา':'ญี่ปุ่นและสหรัฐอเมริกา','แคนนาดา':'แคนาดา','สิงคโปร์ มาเลเซีย และฟิลิปปินส์':'สิงคโปร์ มาเลเซียและฟิลิปปินส์',
'สิงคโปร์ ฟิลิปปินส์ และมาเลเซีย':'สิงคโปร์ ฟิลิปปินส์และมาเลเซีย','สิงคโปร์ และมาเลเซีย':'สิงคโปร์และมาเลเซีย','ไทบ':'ไทย',
'สหราชอาณาจักรและสาธารณรัฐฝรั่งเศส':'สหราชอาณาจักรและฝรั่งเศส','จีน เกาหลีใต้ใต้ใต้':'จีน เกาหลีใต้','สหราชอาณาจักร.':'สหราชอาณาจักร',
'เเบลเยียม เยอรมันนี นอร์เวย์':'เบลเยียม เยอรมนี นอร์เวย์','สวิส':'สมพันธรัฐสวิส','รัฐเซีย':'รัสเซีย','Chaina':'จีน','ราชอาณาจักรกัมพุชา':'กัมพูชา',
'ประชาธิปไตยประชาชนลาว':'ลาว','ไต้หวัน และ จีน':'ไต้หวันและจีน','สหรัฐสหรัฐสหรัฐอเมริกา และ แคนาดา':'สหรัฐอเมริกาและแคนาดา','australia':'ออสเตรเลีย',
'UK':'สหราชอาณาจักร','คาซัคสถาน และสาธารณรัฐตุรกี':'คาซัคสถานและสาธารณรัฐตุรกี', 'จีน และฮ่องกง':'จีนและฮ่องกง',
       'สาธารัฐประชาธิปไตยประชาชนลาว':'ลาว', 'ออสสเตรเลีย':'ออสเตรเลีย',
       'อาณาจักรเนเธอร์แลนด์และสหรัฐสหรัฐสหรัฐอเมริกา':'เนเธอร์แลนด์และสหรัฐอเมริกา', 'Belgium':'เบลเยียม',
       'เวียดนาม และลาว':'เวียดนามและลาว',
       'เยอรมัน และ สวิตเซอร์แลนด์':'เยอรมันและสวิตเซอร์แลนด์', 'สาธารณรัฐประชาธิปไตยประชาชนจีน':'จีน',
     'สาธารณรัฐแห่งสหภาพเมียนมา':'พม่า',
       'สาะารณรับเกาหลีใต้ใต้':'เกาหลีใต้', 'ไท':'ไทย',
       'สหพันธรัฐเยอรมนี':'เยอรมนี', 'สหรัฐสหรัฐอเมริกา':'สหรัฐอเมริกา',
       'สาธารรัฐอินโดนีเซีย':'อินโดนีเซีย', 'กัมพูชา และลาว':'กัมพูชาและลาว', 'สาธารณรัฐอินโดเนีย':'อินโดเนีย',
       'สหภาพเมียนมา':'พม่า', 'สาธารณรัฐแห่งสภาพพม่า':'พม่า',
       'ณ หลวงพระบาง ลาว':'ลาว', 'สาธารณรัฐอินโดนนีเซีย':'อินโดนีเซีย',
       'สาธาธรณรัฐประชาชนจีน':'จีน', 'china':'จีน', 'จีนและเยอรมันนี':'จีนและเยอรมนี',
       'สปป ลาว':'ลาว', 'รพ.ศิริราช   กรุงเทพฯ':'ไทย',
     'เขตบริหารพิเศษฮ่องกง':'ฮ่องกง',  'สาธารณรัฐสิงคโปร์และสหพันธรัฐมาเลเซีย':'สิงคโปร์และมาเลเซีย','สามาพันธรัสสวิส':'สมาพันธรัฐสวิส',
  'สาธารณรัฐประธิปไตยประชาชนลาว':'ลาว','สาธารณรัฐประชาธิปไตรประชาชนลาว':'ลาว','สาธารัฐประชาชนจีน':'จีน',
  'malasia':'มาเลเซีย','สหพันธรัฐมาเลเซีย':'มาเลเซีย','ชลบุรี':'ไทย','สาธารณรัฐประชุาชนจีน':'จีน','สหพันธรัฐมาเลเซียและสาธารณรัฐสิงคโปร์':'มาเลเซียและสิงคโปร์',
  'ไทยเข้าร่วมโครงการ':'ไทย','สาธารณรัฐสังคมนิยมเวียดนาม สาธารณรัฐสิงคโปร์ สหพัน':'เวียดนาม สิงคโปร์','สาธารัฐแอฟริกาใต้':'แอฟริกาใต้',
  'เมียรม่า':'พม่า','เวียดนามและกัมพชา':'เวียดนามและกัมพูชา','Thai':'ไทย','ณ สาธารณรัฐลัตเวีย และสาธารณรัฐลิทัวเนีย':'สาธารณรัฐลัตเวียและสาธารณรัฐลิทัวเนีย',
  'สาธารณรัฐลัตเวีย และ สาธารณรัฐลิทัวเนีย':'สาธารณรัฐลัตเวียและสาธารณรัฐลิทัวเนีย','สาธารณรัฐเมียนมา':'พม่า','สเปน และ อิตาลี':'สเปนและอิตาลี',
  'สาธารณรัฐจีน(ไต้หวัน)':'ไต้หวัน','The Northern of Cyprus':'ไซปรัสเหนือ','มาเลเซีย และ สิงคโปร์':'มาเลเซียและสิงคโปร์','อินโดนีเซีย และ เวียดนาม':'อินโดนีเซียและเวียดนาม',
  'สาธารณรัฐสังคมนิยมเวียดนาน':'เวียดนาม','ออสเตรเลีย และ มาเลเซีย':'ออสเตรเลียและมาเลเซีย',   'Taiwan':'ไต้หวัน', 'กรุงเทพ':'ไทย', 'ป่ารีส':'ปารีส',  'เครือรัฐออสเตรเลีย/นิวซีแลนด์':'ออสเตรเลีย',
       'ติมอร์-เลสเต-เลสเต':'ติมอร์-เลสเต', 'สาธารณรัฐพม่า':'พม่า','South Africa':'แอฟริกาใต้',
       'สาธารณรัฐฝรั่งเศส/สหราชอาณาจักร':'ฝรั่งเศส/สหราชอาณาจักร',
       'ราชอาณาจักรนอร์เวย์และสวีเดน':'นอร์เวย์และสวีเดน', 'สาธารณรัฐอาหรับอียิปต์ และตุรกี':'สาธารณรัฐอาหรับอียิปต์และตุรกี',
       'ฮ่องกงจีน':'ฮ่องกง',
       'สาธารณรัฐสิงคโปร์/มาเลเซีย':'สิงคโปร์/มาเลเซีย',
       'สาธารณรัฐสังคมนิยมเวียดนาม และสาธารณรัฐประชาธิปไตย':'เวียดนาม',
       'เขตปกครองพิเศษฮ่องกง':'ฮ่องกง',
     'สาธารณรัฐสิงคโปร์/มาเลเวีย':'สิงคโปร์/มาเลเซีย', 'Macau':'มาเก๊า',
       'สาธารณรัฐอินโดนีเซีย/เวียดนาม':'อินโดนีเซีย/เวียดนาม', 'สถานที่  ณ  สิงคโปร์':'สิงคโปร์',
       'ลาว สาธารณรัฐสังคมนิยมเ':'ลาว เวียดนาม', 'สหรััฐสหรัฐสหรัฐอเมริกา':'สหรัฐอเมริกา',
       'Czech  Republic':'กรีซ'}

In [21]:
def correct_spelling(word, correction_dict):
    return correction_dict.get(word, word)

In [22]:
df['ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ'] = df['ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ'].apply(lambda x: correct_spelling(x, correction_dict))

In [23]:
print("ข้อมูลหลังทำความสะอาด:")
print(df)

ข้อมูลหลังทำความสะอาด:
       Unnamed: 0 Unnamed: 1            Unnamed: 2  \
0              id   sequence       statuslist-อ้อม
1          100008          2  ฝึกอบรม ณ ต่างประเทศ
2          100008          3       ลาศึกษาในประเทศ
3          100008          4  ลาศึกษา ณ ต่างประเทศ
4          100009          5  ลาศึกษา ณ ต่างประเทศ
...           ...        ...                   ...
230063        NaN        NaN                   NaN
230064        NaN        NaN                   NaN
230065        NaN        NaN                   NaN
230066        NaN        NaN                   NaN
230067        NaN        NaN                   NaN

       ดูข้อมูลจาก ประเภทการลาศึกษา ชีต LoVs           Unnamed: 4  \
0                                ประเภทการลา              details
1                     ไปฝึกอบรม ณ ต่างประเทศ          ภาษาญี่ปุ่น
2                            ลาศึกษาในประเทศ     วิชาญี่ปุ่นศึกษา
3                       ลาศึกษา ณ ต่างประเทศ          ภาษาญี่ปุ่น
4                       ลาศึกษา ณ ต่างประเทศ  Operative Dentistry
...                                      ...                  ...
230063                                   NaN                  NaN
230064                                   NaN                  NaN
230065                                   NaN                  NaN
230066                                   NaN                  NaN
230067                                   NaN                  NaN

               Unnamed: 5 Unnamed: 6  Unnamed: 7  Unnamed: 8  \
0       studylevel-ลิเดีย     Reason        sday        eday
1                     NaN        NaN  1995-09-25  1996-07-09
2                ปริญญาโท   ปริญญาโท  1999-07-01  2001-06-30
3                ปริญญาโท        NaN  2001-03-31  2002-03-30
4            ปริญญาโท-เอก        NaN  1997-04-25  2002-10-24
...                   ...        ...         ...         ...
230063                NaN        NaN         NaN         NaN
230064                NaN        NaN         NaN         NaN
230065                NaN        NaN         NaN         NaN
230066                NaN        NaN         NaN         NaN
230067                NaN        NaN         NaN         NaN

                                          Unnamed: 9  \
0                                          place-เตย
1       Japan Foundation Japanese-Language Institute
2                              มหาวิทยาลัยธรรมศาสตร์
3                                    Keio University
4                                 Indiana University
...                                              ...
230063
230064                                           NaN
230065                                           NaN
230066                                           NaN
230067                                           NaN

                                         Unnamed: 10  \
0                                           location
1       Japan Foundation Japanese-Language Institute
2                              มหาวิทยาลัยธรรมศาสตร์
3                                    Keio University
4                                 Indiana University
...                                              ...
230063                                           NaN
230064                                           NaN
230065                                           NaN
230066                                           NaN
230067                                           NaN

       ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ   Unnamed: 12  \
0                                country-แอน       country
1                                     แคนาดา       ญี่ปุ่น
2                                        ไทย           ไทย
3                                    ญี่ปุ่น       ญี่ปุ่น
4                               สหรัฐอเมริกา  สหรัฐอเมริกา
...                                      ...           ...
230063                                   NaN           NaN
230064                                   NaN           NaN
230065                                   NaN           NaN
230066                                   NaN           NaN
230067                                                 NaN

                                              Unnamed: 13  \
0                                             scholarship
1       The Japan Foundation Japanese Language Insititute
2                                                 ส่วนตัว
3                    Keio University Graduate Scholarship
4                                รัฐบาล (ทบวงมหาวิทยาลัย)
...                                                   ...
230063                                                NaN
230064                                                NaN
230065                                                NaN
230066                                                NaN
230067                                                NaN

                     Unnamed: 14
0                      reference
1         มข.3023/38  ลว.8ก.ย.38
2         มข.1889/42 ลว.2 ก.ค.42
3       มข.1479/44 ลว.20 มิ.ย.44
4        มข.1640/40 ลว.16 พ.ค.40
...                          ...
230063                       NaN
230064                       NaN
230065                       NaN
230066                       NaN
230067                       NaN

[230068 rows x 15 columns]

In [ ]:
import numpy as np

In [ ]:
arr = np.array(['nan'], dtype=object)

In [ ]:
arr = np.where(arr == 'nan', np.nan, arr)

In [ ]:
print(arr)

[nan]

In [ ]:
arr

array([nan], dtype=object)

In [ ]:
df['ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ'] = df['ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ'].astype(str) #เปลี่ยนค่าให้เป็นstr

In [ ]:
df['ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ'] = df['ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ'].astype(str) #เปลี่ยนค่าให้เป็นstr

In [24]:


df["ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ"] = df["ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ"].str.replace('ประเทศ','')
df["ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ"] = df["ดูข้อมูลใน LoVs - ประเทศที่ลาไปศึกษาฯ"].str.replace('+','')

In [33]:

excel_file_path = 'df.xlsx'
# Export the 'merge_data_region' DataFrame to an Excel file
df.to_excel(excel_file_path, index=False)

print(f'DataFrame has been exported to {excel_file_path}')

DataFrame has been exported to df.xlsx

In [34]:
print(f'DataFrame has been exported to {excel_file_path}')

DataFrame has been exported to df.xlsx